[workspace]
members = ["morfeusz-rs", "python", "service", "capi", "cli", "builder"]
resolver = "2"

[workspace.package]
version = "1.99.15"
edition = "2021"
description = "Rust port of the Morfeusz morphological analyzer and generator"
license-file = "License.txt"
readme = "README.md"
repository = "https://github.com/sgjp/morfeusz"
homepage = "https://morfeusz.sgjp.pl"

[workspace.lints.rust]
unused_must_use = "deny"

[workspace.lints.clippy]
all = { level = "deny", priority = -1 }
dbg_macro = "deny"
todo = "deny"
unimplemented = "deny"
too_many_arguments = "allow"
missing_safety_doc = "allow"

[profile.release]
lto = "thin"
codegen-units = 1
