#!/usr/bin/env python3
"""Generate rust/morfeusz-rs/src/case_tables.rs from C++ morfeusz/case/caseconv.cpp.

Morfeusz uses its own 1:1 codepoint->codepoint case tables (NOT Unicode default
casing), and the dictionary FSA keys are lowercased with them at build time. Rust
must use the identical tables or lookups diverge (e.g. Turkish 'İ' U+0130 maps to
'i' here, but to "i̇" under Unicode). This embeds the exact tables.
"""
import re
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
SRC = REPO / "morfeusz" / "case" / "caseconv.cpp"
OUT = REPO / "morfeusz-rs" / "src" / "case_tables.rs"


def parse_flat(text, name):
    m = re.search(name + r"\[\]\s*=\s*\{([^}]*)\}", text)
    return [int(x) for x in m.group(1).split(",") if x.strip()]


def parse_pairs(text, name):
    m = re.search(name + r"\[\]\[2\]\s*=\s*\{(.*?)\};", text, re.S)
    return re.findall(r"\{(\d+),(\d+)\}", m.group(1))


def fmt(nums):
    out, line = [], "    "
    for n in nums:
        piece = f"{n},"
        if len(line) + len(piece) > 96:
            out.append(line)
            line = "    "
        line += piece
    if line.strip():
        out.append(line)
    return "\n".join(out)


def main():
    text = SRC.read_text(encoding="utf-8")
    lower = parse_flat(text, "TO_LOWERCASE_TABLE")
    # C++ stores the extended entries in an (unsorted) std::map; sort them by
    # source codepoint so the Rust side can use binary_search.
    ext_lower = sorted(parse_pairs(text, "EXT_TO_LOWERCASE_TABLE"), key=lambda p: int(p[0]))

    def ext_rs(pairs):
        return ",".join(f"({a},{b})" for a, b in pairs)

    OUT.write_text(f"""//! Case-conversion tables ported verbatim from C++ `morfeusz/case/caseconv.cpp`.
//!
//! Morfeusz uses these 1:1 codepoint->codepoint tables (NOT Unicode default
//! casing) everywhere case matters, and the dictionary FSA keys are lowercased
//! with them at build time. Using Rust's `char::to_lowercase`/`to_uppercase`
//! instead diverges on a handful of codepoints (e.g. U+0130 'İ' -> 'i' here,
//! but -> i + U+0307 combining dot under Unicode), which would make those words
//! fail FSA lookup. GENERATED by `tests/diff_corpus/gen_case_tables.py`.

const TO_LOWERCASE_TABLE: &[u32] = &[
{fmt(lower)}
];

const EXT_TO_LOWERCASE_TABLE: &[(u32, u32)] = &[{ext_rs(ext_lower)}];

fn from_tables(table: &[u32], ext: &[(u32, u32)], codepoint: u32) -> u32 {{
    if (codepoint as usize) < table.len() {{
        table[codepoint as usize]
    }} else if let Ok(index) = ext.binary_search_by_key(&codepoint, |&(from, _)| from) {{
        ext[index].1
    }} else {{
        codepoint
    }}
}}

/// Morfeusz lowercase of a single codepoint (matches C++ `CaseConverter::toLower`).
fn to_lower_cp(codepoint: u32) -> u32 {{
    from_tables(TO_LOWERCASE_TABLE, EXT_TO_LOWERCASE_TABLE, codepoint)
}}

/// Morfeusz lowercase of a `char` (1:1, unlike Unicode `char::to_lowercase`).
pub fn to_lower_char(ch: char) -> char {{
    char::from_u32(to_lower_cp(ch as u32)).unwrap_or(ch)
}}
""", encoding="utf-8")
    print(f"wrote {OUT}: lowercase table={len(lower)} + ext={len(ext_lower)}")


if __name__ == "__main__":
    main()
