use std::collections::{BTreeMap, BTreeSet};
use std::fmt;

use crate::constants::{QualifierSet, MAX_SEGMENT_RULES_FSA_SIZE};
use crate::dictionary::parse_qualifiers;
use crate::error::{validate, BuilderError, Result};
use crate::serialization::{serialize_legacy_string, serialize_u16_be, serialize_u32_be};
use crate::tagset::TagsetRulesLookup;

pub trait SegmentRulesLookup {
    fn lexeme_to_segment_type_num(
        &self,
        base: &str,
        tag_num: usize,
        name_num: usize,
        qualifiers_num: usize,
    ) -> Result<usize>;

    fn should_replace_lemma_with_orth(&self, _segment_type_num: usize) -> bool {
        false
    }

    fn new_segment_type_for_shift_orth(&self, _segment_type_num: usize) -> Option<usize> {
        None
    }
}

pub trait SegmentTypeLookup {
    fn segment_type_num(&self, segment_type: &str) -> Result<usize>;
}

impl SegmentTypeLookup for BTreeMap<String, usize> {
    fn segment_type_num(&self, segment_type: &str) -> Result<usize> {
        self.get(segment_type)
            .copied()
            .ok_or_else(|| BuilderError::new(format!("unknown segment type: {segment_type}")))
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SegmentRule {
    kind: SegmentRuleKind,
    line_number: usize,
    weak: bool,
    autogenerated: bool,
}

#[derive(Debug, Clone, PartialEq, Eq)]
enum SegmentRuleKind {
    Tag {
        segment_type_num: usize,
        shift_orth: bool,
        segment_type: String,
    },
    Concat(Vec<SegmentRule>),
    Or(Vec<SegmentRule>),
    ZeroOrMore(Box<SegmentRule>),
    Optional(Box<SegmentRule>),
    Sink,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub struct SegmentRulesTransitionLabel {
    pub segment_type_num: u8,
    pub shift_orth: bool,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SegmentRulesState {
    pub accepting: bool,
    pub weak: bool,
    pub transitions: BTreeMap<SegmentRulesTransitionLabel, usize>,
    transition_order: Vec<SegmentRulesTransitionLabel>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SegmentRulesFsa {
    pub states: Vec<SegmentRulesState>,
    pub initial_state: usize,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SegmentRulesFsaVariantData {
    pub options: BTreeMap<String, String>,
    pub fsa: Vec<u8>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SegmentRulesTarget {
    Analyzer,
    Generator,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ParsedSegmentRules {
    pub segment_types: Vec<String>,
    pub segment_type_resolver: Option<SegmentTypeResolver>,
    pub separators: Vec<u32>,
    pub variants: Vec<SegmentRulesFsaVariantData>,
    pub default_options: BTreeMap<String, String>,
    pub segmentation_rules_data: Vec<u8>,
    pub replace_lemma_with_orth: BTreeSet<usize>,
    pub shift_orth_extra_segment_types: BTreeMap<usize, usize>,
    pub additional_segment_type_names: BTreeMap<usize, String>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SegmentTypeResolver {
    pub segment_types: Vec<String>,
    segment_type_to_num: BTreeMap<String, usize>,
    segment_nums: BTreeMap<(Option<String>, usize), Vec<SegmentTypeAssignment>>,
    replace_lemma_with_orth: BTreeSet<usize>,
    shift_orth_extra_segment_types: BTreeMap<usize, usize>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct SegmentTypeAssignment {
    homonym: Option<String>,
    name_num: Option<usize>,
    labels_num: usize,
    segment_type_num: usize,
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct SegmentTypePattern {
    lemma: Option<String>,
    homonym: Option<String>,
    pattern: String,
    name: String,
    labels: QualifierSet,
    segment_type_num: usize,
}

impl SegmentRule {
    fn tag(
        segment_type_num: usize,
        shift_orth: bool,
        segment_type: impl Into<String>,
        line_number: usize,
    ) -> Self {
        Self {
            kind: SegmentRuleKind::Tag {
                segment_type_num,
                shift_orth,
                segment_type: segment_type.into(),
            },
            line_number,
            weak: false,
            autogenerated: false,
        }
    }

    fn concat(children: Vec<Self>, line_number: usize) -> Self {
        debug_assert!(!children.is_empty());
        Self {
            kind: SegmentRuleKind::Concat(children),
            line_number,
            weak: false,
            autogenerated: false,
        }
    }

    fn or(children: Vec<Self>, line_number: usize) -> Self {
        debug_assert!(!children.is_empty());
        Self {
            kind: SegmentRuleKind::Or(children),
            line_number,
            weak: false,
            autogenerated: false,
        }
    }

    fn zero_or_more(child: Self, line_number: usize) -> Self {
        Self {
            kind: SegmentRuleKind::ZeroOrMore(Box::new(child)),
            line_number,
            weak: false,
            autogenerated: false,
        }
    }

    fn optional(child: Self, line_number: usize) -> Self {
        Self {
            kind: SegmentRuleKind::Optional(Box::new(child)),
            line_number,
            weak: false,
            autogenerated: false,
        }
    }

    fn sink() -> Self {
        Self {
            kind: SegmentRuleKind::Sink,
            line_number: 0,
            weak: false,
            autogenerated: false,
        }
    }

    pub fn is_weak(&self) -> bool {
        self.weak
    }

    pub fn set_weak(mut self, weak: bool) -> Self {
        self.weak = weak;
        self
    }

    pub fn line_number(&self) -> usize {
        self.line_number
    }

    pub fn is_sink_rule(&self) -> bool {
        matches!(self.kind, SegmentRuleKind::Sink)
    }

    pub fn allows_empty_sequence(&self) -> bool {
        match &self.kind {
            SegmentRuleKind::Tag { .. } => false,
            SegmentRuleKind::Concat(children) => children.iter().all(Self::allows_empty_sequence),
            SegmentRuleKind::Or(children) => children.iter().any(Self::allows_empty_sequence),
            SegmentRuleKind::ZeroOrMore(_) | SegmentRuleKind::Optional(_) => true,
            SegmentRuleKind::Sink => false,
        }
    }

    pub fn is_shift_orth_rule(&self) -> bool {
        match &self.kind {
            SegmentRuleKind::Tag { shift_orth, .. } => *shift_orth,
            SegmentRuleKind::Concat(children) | SegmentRuleKind::Or(children) => {
                children.iter().all(Self::is_shift_orth_rule)
            }
            SegmentRuleKind::ZeroOrMore(child) | SegmentRuleKind::Optional(child) => {
                child.is_shift_orth_rule()
            }
            SegmentRuleKind::Sink => false,
        }
    }

    pub fn make_shift_orth_rule(&mut self) {
        match &mut self.kind {
            SegmentRuleKind::Tag { shift_orth, .. } => *shift_orth = true,
            SegmentRuleKind::Concat(children) | SegmentRuleKind::Or(children) => {
                for child in children {
                    child.make_shift_orth_rule();
                }
            }
            SegmentRuleKind::ZeroOrMore(child) | SegmentRuleKind::Optional(child) => {
                child.make_shift_orth_rule();
            }
            SegmentRuleKind::Sink => {}
        }
    }

    pub fn atomic_rules(&self) -> Vec<&SegmentRule> {
        let mut result = Vec::new();
        self.push_atomic_rules(&mut result);
        result
    }

    fn push_atomic_rules<'a>(&'a self, result: &mut Vec<&'a SegmentRule>) {
        match &self.kind {
            SegmentRuleKind::Tag { .. } => result.push(self),
            SegmentRuleKind::Concat(children) | SegmentRuleKind::Or(children) => {
                for child in children {
                    child.push_atomic_rules(result);
                }
            }
            SegmentRuleKind::ZeroOrMore(child) | SegmentRuleKind::Optional(child) => {
                child.push_atomic_rules(result);
            }
            SegmentRuleKind::Sink => {}
        }
    }

    pub fn transform_to_generator_version(&self) -> Self {
        match &self.kind {
            SegmentRuleKind::Tag { .. } => self.clone(),
            SegmentRuleKind::ZeroOrMore(_) => {
                if self.is_shift_orth_rule() {
                    self.clone()
                } else {
                    Self::sink()
                }
            }
            SegmentRuleKind::Optional(child) => {
                if self.is_shift_orth_rule() {
                    self.clone()
                } else {
                    child.transform_to_generator_version()
                }
            }
            SegmentRuleKind::Or(children) => {
                let new_children: Vec<Self> = children
                    .iter()
                    .filter(|child| !child.allows_empty_sequence() || child.is_shift_orth_rule())
                    .map(Self::transform_to_generator_version)
                    .filter(|child| !child.is_sink_rule())
                    .collect();
                if new_children.is_empty() {
                    Self::sink()
                } else {
                    Self::or(new_children, self.line_number).set_weak(self.weak)
                }
            }
            SegmentRuleKind::Concat(children) => {
                let new_children: Vec<Self> = children
                    .iter()
                    .filter(|child| !child.allows_empty_sequence() || child.is_shift_orth_rule())
                    .map(Self::transform_to_generator_version)
                    .collect();
                if new_children.is_empty() {
                    return Self::sink();
                }
                let mut has_non_optional_non_shifting_rule = false;
                for child in &new_children {
                    if child.is_sink_rule() || has_non_optional_non_shifting_rule {
                        return Self::sink();
                    } else if !child.is_shift_orth_rule() {
                        has_non_optional_non_shifting_rule = true;
                    }
                }
                Self::concat(new_children, self.line_number).set_weak(self.weak)
            }
            SegmentRuleKind::Sink => Self::sink(),
        }
    }

    pub fn additional_atomic_rules_for_generator(&self) -> Vec<Self> {
        match &self.kind {
            SegmentRuleKind::Tag { .. } => {
                let mut rule = self.clone();
                rule.autogenerated = true;
                vec![rule]
            }
            SegmentRuleKind::ZeroOrMore(child) | SegmentRuleKind::Optional(child) => {
                child.additional_atomic_rules_for_generator()
            }
            SegmentRuleKind::Or(children) => children
                .iter()
                .flat_map(Self::additional_atomic_rules_for_generator)
                .collect(),
            SegmentRuleKind::Concat(children) => {
                let mut result = Vec::new();
                let mut current_shift_orth_rule: Option<Self> = None;
                for child in children {
                    if child.is_shift_orth_rule() {
                        current_shift_orth_rule =
                            Some(if let Some(current) = current_shift_orth_rule {
                                Self::concat(vec![current, child.clone()], child.line_number)
                            } else {
                                child.clone()
                            });
                    } else {
                        for atomic_rule in child.additional_atomic_rules_for_generator() {
                            if let Some(current) = &current_shift_orth_rule {
                                result.push(Self::concat(
                                    vec![current.clone(), atomic_rule],
                                    child.line_number,
                                ));
                            } else {
                                result.push(atomic_rule);
                            }
                        }
                        current_shift_orth_rule = None;
                    }
                }
                for rule in &mut result {
                    rule.autogenerated = true;
                }
                result
            }
            SegmentRuleKind::Sink => Vec::new(),
        }
    }

    pub fn validate_segment_rule(&self, input_name: &str) -> Result<()> {
        match &self.kind {
            SegmentRuleKind::Concat(children) => {
                for child in children {
                    child.validate_segment_rule(input_name)?;
                }
                if children.last().is_some_and(Self::is_shift_orth_rule)
                    && !children.iter().all(Self::is_shift_orth_rule)
                {
                    return Err(BuilderError::new(format!(
                        "{input_name}:{} - If the rightmost subrule of concatenation \"{}\" is with \">\", than all subrules must be with \">\"",
                        self.line_number, self
                    )));
                }
                Ok(())
            }
            SegmentRuleKind::Or(children) => {
                for child in children {
                    child.validate_segment_rule(input_name)?;
                }
                let all_shift = children.iter().all(Self::is_shift_orth_rule);
                let any_shift = children.iter().any(Self::is_shift_orth_rule);
                if !all_shift && any_shift {
                    return Err(BuilderError::new(format!(
                        "{input_name}:{} - All subrules of alternative \"{}\" must be either with or without \">\"",
                        self.line_number, self
                    )));
                }
                Ok(())
            }
            SegmentRuleKind::ZeroOrMore(child) | SegmentRuleKind::Optional(child) => {
                child.validate_segment_rule(input_name)
            }
            SegmentRuleKind::Tag { .. } | SegmentRuleKind::Sink => Ok(()),
        }
    }

    fn add_to_segment_rules_nfa(&self, nfa: &mut SegmentRulesNfa) -> Result<()> {
        if self.is_sink_rule() {
            return Ok(());
        }
        let end_state = nfa.add_state(SegmentRulesNfaState::final_for_rule(self));
        self.add_between_segment_rules_nfa_states(nfa, nfa.initial_state, end_state)
    }

    fn add_between_segment_rules_nfa_states(
        &self,
        nfa: &mut SegmentRulesNfa,
        start_state: usize,
        end_state: usize,
    ) -> Result<()> {
        match &self.kind {
            SegmentRuleKind::Tag {
                segment_type_num,
                shift_orth,
                ..
            } => {
                let segment_type_num = u8::try_from(*segment_type_num).map_err(|_| {
                    BuilderError::new(format!(
                        "segment type number {segment_type_num} does not fit into uint8"
                    ))
                })?;
                nfa.add_transition(
                    start_state,
                    Some(SegmentRulesTransitionLabel {
                        segment_type_num,
                        shift_orth: *shift_orth,
                    }),
                    end_state,
                );
                Ok(())
            }
            SegmentRuleKind::Concat(children) => {
                let mut current_start = start_state;
                for child in &children[..children.len() - 1] {
                    let current_end = nfa.add_state(SegmentRulesNfaState::for_rule(self));
                    child.add_between_segment_rules_nfa_states(nfa, current_start, current_end)?;
                    let next_start = nfa.add_state(SegmentRulesNfaState::for_rule(self));
                    nfa.add_transition(current_end, None, next_start);
                    current_start = next_start;
                }
                children
                    .last()
                    .expect("concat is never empty")
                    .add_between_segment_rules_nfa_states(nfa, current_start, end_state)
            }
            SegmentRuleKind::Or(children) => {
                for child in children {
                    let intermediate_start = nfa.add_state(SegmentRulesNfaState::for_rule(self));
                    let intermediate_end = nfa.add_state(SegmentRulesNfaState::for_rule(self));
                    nfa.add_transition(start_state, None, intermediate_start);
                    child.add_between_segment_rules_nfa_states(
                        nfa,
                        intermediate_start,
                        intermediate_end,
                    )?;
                    nfa.add_transition(intermediate_end, None, end_state);
                }
                Ok(())
            }
            SegmentRuleKind::ZeroOrMore(child) => {
                let intermediate_start = nfa.add_state(SegmentRulesNfaState::for_rule(self));
                let intermediate_end = nfa.add_state(SegmentRulesNfaState::for_rule(self));
                nfa.add_transition(start_state, None, intermediate_start);
                nfa.add_transition(start_state, None, end_state);
                child.add_between_segment_rules_nfa_states(
                    nfa,
                    intermediate_start,
                    intermediate_end,
                )?;
                nfa.add_transition(intermediate_end, None, end_state);
                nfa.add_transition(intermediate_end, None, intermediate_start);
                Ok(())
            }
            SegmentRuleKind::Optional(child) => {
                let intermediate_start = nfa.add_state(SegmentRulesNfaState::for_rule(self));
                let intermediate_end = nfa.add_state(SegmentRulesNfaState::for_rule(self));
                nfa.add_transition(start_state, None, intermediate_start);
                nfa.add_transition(start_state, None, end_state);
                child.add_between_segment_rules_nfa_states(
                    nfa,
                    intermediate_start,
                    intermediate_end,
                )?;
                nfa.add_transition(intermediate_end, None, end_state);
                Ok(())
            }
            SegmentRuleKind::Sink => Ok(()),
        }
    }

    fn collect_atomic_rule_info(&self, atoms: &mut Vec<SegmentRuleAtom>) {
        match &self.kind {
            SegmentRuleKind::Tag {
                segment_type_num,
                shift_orth,
                segment_type,
            } => atoms.push(SegmentRuleAtom {
                segment_type_num: *segment_type_num,
                shift_orth: *shift_orth,
                segment_type: segment_type.clone(),
            }),
            SegmentRuleKind::Concat(children) | SegmentRuleKind::Or(children) => {
                for child in children {
                    child.collect_atomic_rule_info(atoms);
                }
            }
            SegmentRuleKind::ZeroOrMore(child) | SegmentRuleKind::Optional(child) => {
                child.collect_atomic_rule_info(atoms);
            }
            SegmentRuleKind::Sink => {}
        }
    }

    fn remap_shift_orth_segment_types(&mut self, shift_orth_map: &BTreeMap<usize, usize>) {
        match &mut self.kind {
            SegmentRuleKind::Tag {
                segment_type_num,
                shift_orth,
                ..
            } => {
                if *shift_orth {
                    if let Some(new_segment_type_num) = shift_orth_map.get(segment_type_num) {
                        *segment_type_num = *new_segment_type_num;
                    }
                }
            }
            SegmentRuleKind::Concat(children) | SegmentRuleKind::Or(children) => {
                for child in children {
                    child.remap_shift_orth_segment_types(shift_orth_map);
                }
            }
            SegmentRuleKind::ZeroOrMore(child) | SegmentRuleKind::Optional(child) => {
                child.remap_shift_orth_segment_types(shift_orth_map);
            }
            SegmentRuleKind::Sink => {}
        }
    }
}

impl fmt::Display for SegmentRule {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match &self.kind {
            SegmentRuleKind::Tag {
                segment_type,
                shift_orth,
                ..
            } => {
                f.write_str(segment_type)?;
                if *shift_orth {
                    f.write_str(">")?;
                }
                Ok(())
            }
            SegmentRuleKind::Concat(children) => {
                for (index, child) in children.iter().enumerate() {
                    if index > 0 {
                        f.write_str(" ")?;
                    }
                    write!(f, "{child}")?;
                }
                Ok(())
            }
            SegmentRuleKind::Or(children) => {
                for (index, child) in children.iter().enumerate() {
                    if index > 0 {
                        f.write_str(" | ")?;
                    }
                    write!(f, "{child}")?;
                }
                Ok(())
            }
            SegmentRuleKind::ZeroOrMore(child) => write!(f, "({child})*"),
            SegmentRuleKind::Optional(child) => write!(f, "({child})?"),
            SegmentRuleKind::Sink => f.write_str("<<REMOVED>>"),
        }
    }
}

pub fn preprocess_segment_rules<I, L, D>(
    input_lines: I,
    active_definitions: D,
    input_name: &str,
) -> Result<Vec<(usize, String)>>
where
    I: IntoIterator<Item = (usize, L)>,
    L: AsRef<str>,
    D: IntoIterator,
    D::Item: AsRef<str>,
{
    let mut defines = BTreeMap::new();
    let active_definitions: BTreeSet<String> = active_definitions
        .into_iter()
        .map(|definition| definition.as_ref().to_owned())
        .collect();
    let mut ifdefs_stack: Vec<(String, bool)> = Vec::new();
    let mut output = Vec::new();

    for (line_number, raw_line) in input_lines {
        let line = raw_line.as_ref();
        if line.starts_with("#define") {
            let parsed = parse_segment_rule_define(line, line_number, input_name)?;
            match parsed {
                SegmentRuleDefine::WithoutArg { name, value } => {
                    defines.insert(name.clone(), SegmentRuleDefineValue::WithoutArg(value));
                }
                SegmentRuleDefine::WithArg { name, arg, value } => {
                    defines.insert(name, SegmentRuleDefineValue::WithArg { arg, value });
                }
            }
        } else if line.starts_with("#ifdef") {
            let name = parse_segment_rule_ifdef(line, line_number, input_name)?;
            ifdefs_stack.push((name, true));
        } else if line.starts_with("#else") {
            let Some((name, is_active)) = ifdefs_stack.last_mut() else {
                return Err(BuilderError::new(format!(
                    "{input_name}:{line_number}: #else without #ifdef"
                )));
            };
            validate(
                *is_active,
                format!("{input_name}:{line_number}: repeated #else for #ifdef {name}"),
            )?;
            *is_active = false;
        } else if line.starts_with("#endif") {
            if ifdefs_stack.pop().is_none() {
                return Err(BuilderError::new(format!(
                    "{input_name}:{line_number}: #endif without #ifdef"
                )));
            }
        } else if line.starts_with('#') {
            output.push((line_number, line.to_owned()));
        } else if segment_rule_ifdefs_active(&ifdefs_stack, &active_definitions) {
            output.push((
                line_number,
                process_segment_rule_line(line_number, line, &defines, input_name)?,
            ));
        }
    }

    validate(
        ifdefs_stack.is_empty(),
        format!("{input_name}: unterminated #ifdef in segmentation rules"),
    )?;
    Ok(output)
}

pub fn parse_segment_rule_line<T>(
    line_number: usize,
    line: &str,
    segment_types: &T,
    input_name: &str,
) -> Result<SegmentRule>
where
    T: SegmentTypeLookup,
{
    SegmentRuleParser::new(line_number, line, segment_types, input_name).parse_complete_rule()
}

pub fn build_segment_rules_fsa<'a, I>(rules: I, input_name: &str) -> Result<SegmentRulesFsa>
where
    I: IntoIterator<Item = &'a SegmentRule>,
{
    let mut nfa = SegmentRulesNfa::new();
    for rule in rules {
        rule.add_to_segment_rules_nfa(&mut nfa)?;
    }
    nfa.convert_to_dfa(input_name)
}

pub fn serialize_segment_rules_fsa<'a, I>(rules: I, input_name: &str) -> Result<Vec<u8>>
where
    I: IntoIterator<Item = &'a SegmentRule>,
{
    let fsa = build_segment_rules_fsa(rules, input_name)?;
    serialize_segment_rules_fsa_data(&fsa)
}

pub fn calculate_segment_rules_fsa_layout(fsa: &SegmentRulesFsa) -> Result<SegmentRulesFsaLayout> {
    validate_segment_rules_fsa(fsa)?;
    let dfs_order = segment_rules_fsa_dfs_order(fsa)?;
    let mut reverse_offsets = vec![0; fsa.states.len()];
    let mut current_reverse_offset = 0usize;

    for &state_index in &dfs_order {
        current_reverse_offset += segment_rules_state_size(&fsa.states[state_index])?;
        reverse_offsets[state_index] = current_reverse_offset;
    }

    let total_size = current_reverse_offset;
    let mut offsets = vec![0; fsa.states.len()];
    for &state_index in &dfs_order {
        offsets[state_index] = total_size - reverse_offsets[state_index];
    }

    Ok(SegmentRulesFsaLayout {
        dfs_order,
        offsets,
        reverse_offsets,
        total_size,
    })
}

pub fn serialize_segment_rules_fsa_data(fsa: &SegmentRulesFsa) -> Result<Vec<u8>> {
    let layout = calculate_segment_rules_fsa_layout(fsa)?;
    validate(
        layout.total_size <= MAX_SEGMENT_RULES_FSA_SIZE,
        format!(
            "Segmentation rules are too big and complicated- the resulting automaton would exceed its max size which is {}",
            MAX_SEGMENT_RULES_FSA_SIZE
        ),
    )?;

    let mut ordered_states = layout.dfs_order.clone();
    ordered_states.sort_by_key(|state_index| layout.offsets[*state_index]);

    let mut out = Vec::with_capacity(layout.total_size);
    for state_index in ordered_states {
        out.extend(serialize_segment_rules_state(
            &fsa.states[state_index],
            &layout,
        )?);
    }
    Ok(out)
}

pub fn serialize_segmentation_rules_data<I>(
    separators: I,
    variants: &[SegmentRulesFsaVariantData],
    default_options: &BTreeMap<String, String>,
) -> Result<Vec<u8>>
where
    I: IntoIterator<Item = u32>,
{
    validate(
        !variants.is_empty() && variants.len() < 256,
        "Too many segmentation rules variants",
    )?;

    let mut out = Vec::new();
    let mut separators: Vec<u32> = separators.into_iter().collect();
    separators.sort_unstable();
    out.extend(serialize_u16_be(separators.len())?);
    for separator in separators {
        out.extend(serialize_u32_be(separator as usize)?);
    }

    out.push(variants.len() as u8);
    for variant in variants {
        out.extend(serialize_segment_rules_options_map(&variant.options)?);
        out.extend(serialize_u32_be(variant.fsa.len())?);
        out.extend(&variant.fsa);
    }
    out.extend(serialize_segment_rules_options_map(default_options)?);
    Ok(out)
}

pub fn parse_segmentation_rules_from_str(
    input_name: &str,
    input: &str,
    target: SegmentRulesTarget,
) -> Result<ParsedSegmentRules> {
    let config = SegmentRulesConfigFile::parse(
        input_name,
        input,
        [
            "options",
            "combinations",
            "tags",
            "lexemes",
            "segment types",
            "separator chars",
        ],
    )?;
    let segment_types = parse_segment_types_section(&config)?;
    parse_segmentation_rules_config(input_name, &config, target, segment_types, None)
}

pub fn parse_segmentation_rules_with_tagset_from_str<T>(
    input_name: &str,
    input: &str,
    target: SegmentRulesTarget,
    tagset: &T,
    names_map: &BTreeMap<String, usize>,
    labels_map: &BTreeMap<QualifierSet, usize>,
) -> Result<ParsedSegmentRules>
where
    T: TagsetRulesLookup,
{
    let config = SegmentRulesConfigFile::parse(
        input_name,
        input,
        [
            "options",
            "combinations",
            "tags",
            "lexemes",
            "segment types",
            "separator chars",
        ],
    )?;
    let segment_types = parse_segment_types_section(&config)?;
    let segment_type_resolver = SegmentTypeResolver::from_config(
        &config,
        segment_types.clone(),
        tagset,
        names_map,
        labels_map,
    )?;
    parse_segmentation_rules_config(
        input_name,
        &config,
        target,
        segment_types,
        Some(segment_type_resolver),
    )
}

fn parse_segmentation_rules_config(
    input_name: &str,
    config: &SegmentRulesConfigFile,
    target: SegmentRulesTarget,
    segment_types: Vec<String>,
    segment_type_resolver: Option<SegmentTypeResolver>,
) -> Result<ParsedSegmentRules> {
    let option_definitions = parse_segment_rules_options(config)?;
    let segment_type_nums: BTreeMap<String, usize> = segment_types
        .iter()
        .enumerate()
        .map(|(index, segment_type)| (segment_type.clone(), index))
        .collect();
    let separators = if target == SegmentRulesTarget::Analyzer {
        parse_separator_chars_section(config)?
    } else {
        Vec::new()
    };

    let definitions_to_option_keys = definitions_to_option_keys(&option_definitions);
    let option_combinations = segment_rules_option_combinations(&option_definitions);
    let combination_lines = config.lines_in_section("combinations", false)?;
    let mut rules_by_options = Vec::new();

    for active_definitions in option_combinations {
        let options =
            active_definitions_to_options(&active_definitions, &definitions_to_option_keys)?;
        let preprocessed = preprocess_segment_rules(
            combination_lines.iter().cloned(),
            &active_definitions,
            input_name,
        )?;
        let mut rules = Vec::new();
        for (line_number, line) in preprocessed {
            if line.starts_with('#') {
                continue;
            }
            let mut rule =
                parse_segment_rule_line(line_number, &line, &segment_type_nums, input_name)?;
            if rule.allows_empty_sequence() {
                return Err(BuilderError::new(format!(
                    "{input_name}:{line_number} - This rule allows empty segments sequence to be accepted"
                )));
            }
            rule.validate_segment_rule(input_name)?;
            if target == SegmentRulesTarget::Generator {
                let mut additional_rules = rule.additional_atomic_rules_for_generator();
                for additional_rule in &mut additional_rules {
                    additional_rule.autogenerated = true;
                }
                rules.extend(additional_rules);
                rule = rule.transform_to_generator_version();
            }
            if !rule.is_sink_rule() {
                rules.push(rule);
            }
        }
        rules_by_options.push((options, rules));
    }

    let shift_magic = apply_shift_orth_magic(&segment_types, &mut rules_by_options);
    let mut variants = Vec::with_capacity(rules_by_options.len());
    for (options, rules) in &rules_by_options {
        variants.push(SegmentRulesFsaVariantData {
            options: options.clone(),
            fsa: serialize_segment_rules_fsa(rules.iter(), input_name)?,
        });
    }
    let default_options = variants
        .first()
        .map(|variant| variant.options.clone())
        .ok_or_else(|| BuilderError::new("Too many segmentation rules variants"))?;
    let segmentation_rules_data =
        serialize_segmentation_rules_data(separators.iter().copied(), &variants, &default_options)?;

    Ok(ParsedSegmentRules {
        segment_types,
        segment_type_resolver: segment_type_resolver.map(|resolver| {
            resolver.with_shift_magic(
                shift_magic.replace_lemma_with_orth.clone(),
                shift_magic.shift_orth_extra_segment_types.clone(),
            )
        }),
        separators,
        variants,
        default_options,
        segmentation_rules_data,
        replace_lemma_with_orth: shift_magic.replace_lemma_with_orth,
        shift_orth_extra_segment_types: shift_magic.shift_orth_extra_segment_types,
        additional_segment_type_names: shift_magic.additional_segment_type_names,
    })
}

fn validate_segment_rules_fsa(fsa: &SegmentRulesFsa) -> Result<()> {
    validate(!fsa.states.is_empty(), "empty segmentation rules FSA")?;
    validate(
        fsa.initial_state < fsa.states.len(),
        format!(
            "invalid segmentation rules initial state index: {}",
            fsa.initial_state
        ),
    )?;
    for (state_index, state) in fsa.states.iter().enumerate() {
        validate(
            state.transitions.len() <= u8::MAX as usize,
            format!(
                "segmentation rules state {state_index} has too many transitions: {}",
                state.transitions.len()
            ),
        )?;
        validate(
            state.transition_order.len() == state.transitions.len(),
            format!("segmentation rules state {state_index} transition order is inconsistent"),
        )?;
        for label in &state.transition_order {
            validate(
                state.transitions.contains_key(label),
                format!("segmentation rules state {state_index} transition order has stale label"),
            )?;
        }
        for target in state.transitions.values() {
            validate(
                *target < fsa.states.len(),
                format!("segmentation rules state {state_index} targets invalid state {target}"),
            )?;
        }
    }
    Ok(())
}

fn segment_rules_fsa_dfs_order(fsa: &SegmentRulesFsa) -> Result<Vec<usize>> {
    let mut visited = vec![false; fsa.states.len()];
    let mut order = Vec::new();
    segment_rules_fsa_dfs_visit(fsa, fsa.initial_state, &mut visited, &mut order)?;
    Ok(order)
}

fn segment_rules_fsa_dfs_visit(
    fsa: &SegmentRulesFsa,
    state_index: usize,
    visited: &mut [bool],
    order: &mut Vec<usize>,
) -> Result<()> {
    if visited[state_index] {
        return Ok(());
    }
    visited[state_index] = true;

    for label in &fsa.states[state_index].transition_order {
        let target = fsa.states[state_index]
            .transitions
            .get(label)
            .ok_or_else(|| {
                BuilderError::new(format!(
                    "segmentation rules state {state_index} transition order has stale label"
                ))
            })?;
        validate(
            *target < fsa.states.len(),
            format!("segmentation rules state {state_index} targets invalid state {target}"),
        )?;
        segment_rules_fsa_dfs_visit(fsa, *target, visited, order)?;
    }

    order.push(state_index);
    Ok(())
}

fn segment_rules_state_size(state: &SegmentRulesState) -> Result<usize> {
    validate(
        state.transitions.len() <= u8::MAX as usize,
        format!(
            "segmentation rules state has too many transitions: {}",
            state.transitions.len()
        ),
    )?;
    Ok(2 + 4 * state.transitions.len())
}

fn serialize_segment_rules_state(
    state: &SegmentRulesState,
    layout: &SegmentRulesFsaLayout,
) -> Result<Vec<u8>> {
    let mut out = Vec::with_capacity(segment_rules_state_size(state)?);
    let mut flags = 0u8;
    if state.accepting {
        flags |= 1;
    }
    if state.weak {
        flags |= 2;
    }
    out.push(flags);
    out.push(state.transitions.len() as u8);
    for (label, target) in &state.transitions {
        let target_offset = layout.offsets[*target];
        validate(
            target_offset <= MAX_SEGMENT_RULES_FSA_SIZE,
            format!(
                "Segmentation rules are too big and complicated- the resulting automaton would exceed its max size which is {}",
                MAX_SEGMENT_RULES_FSA_SIZE
            ),
        )?;
        out.push(label.segment_type_num);
        out.push(u8::from(label.shift_orth));
        out.extend(serialize_u16_be(target_offset)?);
    }
    Ok(out)
}

fn serialize_segment_rules_options_map(options: &BTreeMap<String, String>) -> Result<Vec<u8>> {
    let aggl = options
        .get("aggl")
        .ok_or_else(|| BuilderError::new("segmentation options missing aggl"))?;
    let praet = options
        .get("praet")
        .ok_or_else(|| BuilderError::new("segmentation options missing praet"))?;
    let mut out = Vec::new();
    out.push(2);
    out.extend(serialize_legacy_string("aggl"));
    out.extend(serialize_legacy_string(aggl));
    out.extend(serialize_legacy_string("praet"));
    out.extend(serialize_legacy_string(praet));
    Ok(out)
}

struct SegmentRulesConfigFile {
    input_name: String,
    section_names: BTreeSet<String>,
    section_lines: BTreeMap<String, Vec<(usize, String)>>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct SegmentRuleAtom {
    segment_type_num: usize,
    shift_orth: bool,
    segment_type: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Default)]
struct ShiftOrthMagicData {
    replace_lemma_with_orth: BTreeSet<usize>,
    shift_orth_extra_segment_types: BTreeMap<usize, usize>,
    additional_segment_type_names: BTreeMap<usize, String>,
}

impl SegmentRulesConfigFile {
    fn parse<I, S>(input_name: &str, input: &str, section_names: I) -> Result<Self>
    where
        I: IntoIterator<Item = S>,
        S: AsRef<str>,
    {
        let section_names: BTreeSet<String> = section_names
            .into_iter()
            .map(|section_name| section_name.as_ref().to_owned())
            .collect();
        let mut section_lines = BTreeMap::new();
        let mut current_section: Option<String> = None;

        for (line_index, raw_line) in input.lines().enumerate() {
            let line_number = line_index + 1;
            if let Some(section_name) = segment_rules_header_value(raw_line) {
                validate(
                    section_names.contains(&section_name),
                    format!("{input_name}:{line_number} - Invalid section: {section_name}"),
                )?;
                validate(
                    !section_lines.contains_key(&section_name),
                    format!("{input_name}:{line_number} - Duplicate section: {section_name}"),
                )?;
                section_lines.insert(section_name.clone(), Vec::new());
                current_section = Some(section_name);
            } else {
                let line = raw_line.trim();
                if line.is_empty() {
                    continue;
                }
                let Some(section_name) = current_section.as_ref() else {
                    if line.starts_with('#') {
                        continue;
                    }
                    return Err(BuilderError::new(format!(
                        "{input_name}:{line_number} - Text outside of any section"
                    )));
                };
                section_lines
                    .get_mut(section_name)
                    .expect("current section was inserted")
                    .push((line_number, line.to_owned()));
            }
        }

        Ok(Self {
            input_name: input_name.to_owned(),
            section_names,
            section_lines,
        })
    }

    fn lines_in_section(
        &self,
        section_name: &str,
        ignore_comments: bool,
    ) -> Result<Vec<(usize, String)>> {
        validate(
            self.section_names.contains(section_name),
            format!("invalid known section request: {section_name}"),
        )?;
        let lines = self.section_lines.get(section_name).ok_or_else(|| {
            BuilderError::new(format!(
                "{} - Missing section: \"{}\"",
                self.input_name, section_name
            ))
        })?;
        Ok(lines
            .iter()
            .filter(|(_line_number, line)| !ignore_comments || !line.starts_with('#'))
            .cloned()
            .collect())
    }
}

fn segment_rules_header_value(line: &str) -> Option<String> {
    let line = line.trim_start();
    let rest = line.strip_prefix('[')?;
    let end = rest.find(']')?;
    Some(rest[..end].to_owned())
}

fn parse_segment_rules_options(
    config: &SegmentRulesConfigFile,
) -> Result<Vec<(String, Vec<String>)>> {
    let mut options = Vec::new();
    for (line_number, line) in config.lines_in_section("options", true)? {
        let (key, values) = line.split_once('=').ok_or_else(|| {
            BuilderError::new(format!(
                "{}:{line_number} - Error in [options] section: missing '='",
                config.input_name
            ))
        })?;
        let key = key.trim();
        validate(
            is_ascii_word(key),
            format!(
                "{}:{line_number} - Error in [options] section: invalid option key: {key}",
                config.input_name
            ),
        )?;
        let values: Vec<String> = values.split_whitespace().map(str::to_owned).collect();
        validate(
            !values.is_empty() && values.iter().all(|value| is_ascii_word(value)),
            format!(
                "{}:{line_number} - Error in [options] section: invalid option values",
                config.input_name
            ),
        )?;
        options.push((key.to_owned(), values));
    }
    Ok(options)
}

fn parse_segment_types_section(config: &SegmentRulesConfigFile) -> Result<Vec<String>> {
    let mut segment_types = Vec::new();
    for (line_number, line) in config.lines_in_section("segment types", true)? {
        validate(
            is_ascii_word(&line),
            format!(
                "{}:{line_number} - Segment type must be a single word",
                config.input_name
            ),
        )?;
        validate(
            !segment_types.contains(&line),
            format!(
                "{}:{line_number} - Segment type already defined: \"{}\"",
                config.input_name, line
            ),
        )?;
        segment_types.push(line);
    }
    Ok(segment_types)
}

fn parse_separator_chars_section(config: &SegmentRulesConfigFile) -> Result<Vec<u32>> {
    let mut separators = Vec::new();
    for (line_number, line) in config.lines_in_section("separator chars", true)? {
        let separator = line.parse::<u32>().map_err(|err| {
            BuilderError::new(format!("{}:{line_number} - {err}", config.input_name))
        })?;
        separators.push(separator);
    }
    Ok(separators)
}

fn definitions_to_option_keys(
    option_definitions: &[(String, Vec<String>)],
) -> BTreeMap<String, String> {
    let mut definitions_to_option_keys = BTreeMap::new();
    for (key, definitions) in option_definitions {
        for definition in definitions {
            definitions_to_option_keys.insert(definition.clone(), key.clone());
        }
    }
    definitions_to_option_keys
}

fn segment_rules_option_combinations(
    option_definitions: &[(String, Vec<String>)],
) -> Vec<Vec<String>> {
    let mut combinations = vec![Vec::new()];
    for (_key, definitions) in option_definitions {
        let mut next = Vec::new();
        for combination in &combinations {
            for definition in definitions {
                let mut combination = combination.clone();
                combination.push(definition.clone());
                next.push(combination);
            }
        }
        combinations = next;
    }
    combinations
}

fn active_definitions_to_options(
    active_definitions: &[String],
    definitions_to_option_keys: &BTreeMap<String, String>,
) -> Result<BTreeMap<String, String>> {
    let mut options = BTreeMap::new();
    for definition in active_definitions {
        let key = definitions_to_option_keys.get(definition).ok_or_else(|| {
            BuilderError::new(format!("missing option key for definition {definition}"))
        })?;
        options.insert(key.clone(), definition.clone());
    }
    Ok(options)
}

fn apply_shift_orth_magic(
    segment_types: &[String],
    rules_by_options: &mut [(BTreeMap<String, String>, Vec<SegmentRule>)],
) -> ShiftOrthMagicData {
    let mut shift_orth_segment_types = BTreeSet::new();
    let mut non_shift_orth_segment_types = BTreeSet::new();

    for (_options, rules) in rules_by_options.iter() {
        for rule in rules {
            let mut atoms = Vec::new();
            rule.collect_atomic_rule_info(&mut atoms);
            for atom in atoms {
                if atom.shift_orth {
                    shift_orth_segment_types.insert(atom.segment_type);
                } else {
                    non_shift_orth_segment_types.insert(atom.segment_type);
                }
            }
        }
    }

    let mut result = ShiftOrthMagicData::default();
    let mut next_new_segment_type_num = segment_types.len();
    for (segment_type_num, segment_type) in segment_types.iter().enumerate() {
        if shift_orth_segment_types.contains(segment_type)
            && non_shift_orth_segment_types.contains(segment_type)
        {
            result
                .shift_orth_extra_segment_types
                .insert(segment_type_num, next_new_segment_type_num);
            result
                .additional_segment_type_names
                .insert(next_new_segment_type_num, format!("{segment_type}>"));
            next_new_segment_type_num += 1;
        } else if shift_orth_segment_types.contains(segment_type) {
            result.replace_lemma_with_orth.insert(segment_type_num);
        }
    }

    for (_options, rules) in rules_by_options {
        for rule in rules {
            rule.remap_shift_orth_segment_types(&result.shift_orth_extra_segment_types);
        }
    }

    result
}

fn is_ascii_word(value: &str) -> bool {
    !value.is_empty()
        && value
            .chars()
            .all(|ch| ch.is_ascii_alphanumeric() || ch == '_')
}

impl SegmentTypeResolver {
    fn from_config<T>(
        config: &SegmentRulesConfigFile,
        segment_types: Vec<String>,
        tagset: &T,
        names_map: &BTreeMap<String, usize>,
        labels_map: &BTreeMap<QualifierSet, usize>,
    ) -> Result<Self>
    where
        T: TagsetRulesLookup,
    {
        let segment_type_to_num: BTreeMap<String, usize> = segment_types
            .iter()
            .enumerate()
            .map(|(index, segment_type)| (segment_type.clone(), index))
            .collect();
        let mut patterns = Vec::new();
        for (line_number, line) in config.lines_in_section("lexemes", true)? {
            patterns.push(parse_segment_type_pattern(
                config,
                line_number,
                &line,
                true,
                &segment_type_to_num,
                tagset,
            )?);
        }

        let mut got_wildcard_pattern = false;
        let mut last_tag_line_number = None;
        for (line_number, line) in config.lines_in_section("tags", true)? {
            patterns.push(parse_segment_type_pattern(
                config,
                line_number,
                &line,
                false,
                &segment_type_to_num,
                tagset,
            )?);
            validate(
                !got_wildcard_pattern,
                format!(
                    "{}:{} - Pattern that matches everything must be the last one",
                    config.input_name,
                    line_number.saturating_sub(1)
                ),
            )?;
            got_wildcard_pattern = patterns
                .last()
                .expect("just pushed tag pattern")
                .is_wildcard_pattern();
            last_tag_line_number = Some(line_number);
        }
        let line_number = last_tag_line_number.unwrap_or_default();
        validate(
            patterns.last().is_some_and(SegmentTypePattern::is_wildcard_pattern),
            format!(
                "{}:{line_number} - There must be a pattern that matches everything at the end of [tags] section",
                config.input_name
            ),
        )?;

        let mut resolver = Self {
            segment_types,
            segment_type_to_num,
            segment_nums: BTreeMap::new(),
            replace_lemma_with_orth: BTreeSet::new(),
            shift_orth_extra_segment_types: BTreeMap::new(),
        };
        resolver.index_patterns(patterns, tagset, names_map, labels_map)?;
        Ok(resolver)
    }

    fn with_shift_magic(
        mut self,
        replace_lemma_with_orth: BTreeSet<usize>,
        shift_orth_extra_segment_types: BTreeMap<usize, usize>,
    ) -> Self {
        self.replace_lemma_with_orth = replace_lemma_with_orth;
        self.shift_orth_extra_segment_types = shift_orth_extra_segment_types;
        self
    }

    fn index_patterns<T>(
        &mut self,
        patterns: Vec<SegmentTypePattern>,
        tagset: &T,
        names_map: &BTreeMap<String, usize>,
        labels_map: &BTreeMap<QualifierSet, usize>,
    ) -> Result<()>
    where
        T: TagsetRulesLookup,
    {
        for pattern in patterns {
            for tag in tagset.all_tags() {
                if pattern.matches_tag(tag) {
                    let tag_num = tagset.tag_num(tag)?;
                    let name_num = names_map.get(&pattern.name).copied();
                    for labels_num in existing_labels_num_combinations(&pattern.labels, labels_map)
                    {
                        self.segment_nums
                            .entry((pattern.lemma.clone(), tag_num))
                            .or_default()
                            .push(SegmentTypeAssignment {
                                homonym: pattern.homonym.clone(),
                                name_num,
                                labels_num,
                                segment_type_num: pattern.segment_type_num,
                            });
                    }
                }
            }
        }
        Ok(())
    }

    fn lookup_segment_type_num(
        &self,
        lemma: Option<&str>,
        tag_num: usize,
        name_num: usize,
        labels_num: usize,
    ) -> Option<usize> {
        let (lemma, homonym) = split_lemma_homonym(lemma);
        if let Some(assignments) = self.segment_nums.get(&(lemma.clone(), tag_num)) {
            for assignment in assignments {
                if assignment.homonym == homonym
                    && segment_type_assignment_matches(assignment, name_num, labels_num)
                {
                    return Some(assignment.segment_type_num);
                }
            }
        }

        if homonym.is_some() {
            self.lookup_segment_type_num(lemma.as_deref(), tag_num, name_num, labels_num)
        } else if lemma.is_some() {
            self.lookup_segment_type_num(None, tag_num, name_num, labels_num)
        } else {
            None
        }
    }
}

impl SegmentTypeLookup for SegmentTypeResolver {
    fn segment_type_num(&self, segment_type: &str) -> Result<usize> {
        self.segment_type_to_num
            .get(segment_type)
            .copied()
            .ok_or_else(|| BuilderError::new(format!("unknown segment type: {segment_type}")))
    }
}

impl SegmentRulesLookup for SegmentTypeResolver {
    fn lexeme_to_segment_type_num(
        &self,
        base: &str,
        tag_num: usize,
        name_num: usize,
        qualifiers_num: usize,
    ) -> Result<usize> {
        self.lookup_segment_type_num(Some(base), tag_num, name_num, qualifiers_num)
            .ok_or_else(|| {
                BuilderError::new(format!(
                    "missing segment type for {base}/{tag_num}/{name_num}/{qualifiers_num}"
                ))
            })
    }

    fn should_replace_lemma_with_orth(&self, segment_type_num: usize) -> bool {
        self.replace_lemma_with_orth.contains(&segment_type_num)
    }

    fn new_segment_type_for_shift_orth(&self, segment_type_num: usize) -> Option<usize> {
        self.shift_orth_extra_segment_types
            .get(&segment_type_num)
            .copied()
    }
}

impl SegmentRulesLookup for ParsedSegmentRules {
    fn lexeme_to_segment_type_num(
        &self,
        base: &str,
        tag_num: usize,
        name_num: usize,
        qualifiers_num: usize,
    ) -> Result<usize> {
        self.segment_type_resolver
            .as_ref()
            .ok_or_else(|| BuilderError::new("segmentation rules were parsed without tagset data"))?
            .lexeme_to_segment_type_num(base, tag_num, name_num, qualifiers_num)
    }

    fn should_replace_lemma_with_orth(&self, segment_type_num: usize) -> bool {
        self.segment_type_resolver
            .as_ref()
            .is_some_and(|resolver| resolver.should_replace_lemma_with_orth(segment_type_num))
    }

    fn new_segment_type_for_shift_orth(&self, segment_type_num: usize) -> Option<usize> {
        self.segment_type_resolver
            .as_ref()
            .and_then(|resolver| resolver.new_segment_type_for_shift_orth(segment_type_num))
    }
}

impl SegmentTypePattern {
    fn matches_tag(&self, tag: &str) -> bool {
        segment_type_pattern_matches_tag(&self.pattern, tag)
    }

    fn is_wildcard_pattern(&self) -> bool {
        self.lemma.is_none()
            && self.pattern == "%"
            && self.name.is_empty()
            && self.labels.is_empty()
    }
}

fn parse_segment_type_pattern<T>(
    config: &SegmentRulesConfigFile,
    line_number: usize,
    line: &str,
    with_lemma: bool,
    segment_type_to_num: &BTreeMap<String, usize>,
    tagset: &T,
) -> Result<SegmentTypePattern>
where
    T: TagsetRulesLookup,
{
    let fields: Vec<&str> = line.split_whitespace().collect();
    let (segment_type, lemma, pattern, constraint_fields) = if with_lemma {
        validate(
            (3..=5).contains(&fields.len()),
            format!(
                "{}:{line_number} - Line in [lexemes] section must contain 3 to 5 fields - segment type, lemma, tag pattern and optional constraints on name and labels",
                config.input_name
            ),
        )?;
        (fields[0], Some(fields[1]), fields[2], &fields[3..])
    } else {
        validate(
            (2..=4).contains(&fields.len()),
            format!(
                "{}:{line_number} - Line in [tags] section must contain 2 to 4 fields - segment type, tag pattern and optional constraints on name and labels",
                config.input_name
            ),
        )?;
        (fields[0], None, fields[1], &fields[2..])
    };

    let segment_type_num = segment_type_to_num
        .get(segment_type)
        .copied()
        .ok_or_else(|| {
            BuilderError::new(format!(
                "{}:{line_number} - Undeclared segment type: \"{}\"",
                config.input_name, segment_type
            ))
        })?;

    validate(
        is_legacy_segment_type_pattern(pattern),
        format!(
            "{}:{line_number} - Pattern must contain only \":\", \"%\", \".\" and lowercase alphanumeric letters",
            config.input_name
        ),
    )?;

    let constraints = parse_segment_type_constraints(config, line_number, constraint_fields)?;
    let (lemma, homonym) = split_lemma_homonym(lemma);
    let segment_type_pattern = SegmentTypePattern {
        lemma,
        homonym,
        pattern: pattern.to_owned(),
        name: constraints.name.unwrap_or_default(),
        labels: constraints.labels.unwrap_or_default(),
        segment_type_num,
    };
    validate(
        tagset
            .all_tags()
            .iter()
            .any(|tag| segment_type_pattern.matches_tag(tag)),
        format!(
            "{}:{line_number} - There is no tag that matches pattern \"{}\".",
            config.input_name, pattern
        ),
    )?;
    Ok(segment_type_pattern)
}

#[derive(Debug, Clone, PartialEq, Eq, Default)]
struct SegmentTypeConstraints {
    name: Option<String>,
    labels: Option<QualifierSet>,
}

fn parse_segment_type_constraints(
    config: &SegmentRulesConfigFile,
    line_number: usize,
    fields: &[&str],
) -> Result<SegmentTypeConstraints> {
    let mut constraints = SegmentTypeConstraints::default();
    for field in fields {
        let (key, value) = field.split_once('=').ok_or_else(|| {
            BuilderError::new(format!(
                "{}:{line_number} - invalid name or labels constraint: \"{}\"",
                config.input_name, field
            ))
        })?;
        validate(
            matches!(key, "name" | "labels")
                && !value.is_empty()
                && !value.chars().any(char::is_whitespace),
            format!(
                "{}:{line_number} - invalid name or labels constraint: \"{}\"",
                config.input_name, field
            ),
        )?;
        match key {
            "name" => {
                validate(
                    constraints.name.is_none(),
                    format!(
                        "{}:{line_number} - name already specified",
                        config.input_name
                    ),
                )?;
                constraints.name = Some(value.to_owned());
            }
            "labels" => {
                validate(
                    constraints.labels.is_none(),
                    format!(
                        "{}:{line_number} - labels already specified",
                        config.input_name
                    ),
                )?;
                constraints.labels = Some(parse_qualifiers(value));
            }
            _ => unreachable!("key validated"),
        }
    }
    Ok(constraints)
}

fn existing_labels_num_combinations(
    labels: &QualifierSet,
    labels_map: &BTreeMap<QualifierSet, usize>,
) -> Vec<usize> {
    if labels.is_empty() {
        vec![0]
    } else {
        labels_map
            .iter()
            .filter_map(|(labels_combination, labels_num)| {
                labels.is_subset(labels_combination).then_some(*labels_num)
            })
            .collect()
    }
}

fn segment_type_assignment_matches(
    assignment: &SegmentTypeAssignment,
    name_num: usize,
    labels_num: usize,
) -> bool {
    matches!(
        (assignment.name_num, assignment.labels_num),
        (Some(n), l)
            if (n, l) == (name_num, labels_num)
                || (n, l) == (0, 0)
                || (n == 0 && l == labels_num)
                || (l == 0 && n == name_num)
    )
}

fn split_lemma_homonym(lemma: Option<&str>) -> (Option<String>, Option<String>) {
    match lemma {
        None => (None, None),
        Some(lemma) if lemma.contains(':') && !lemma.replace(':', "").is_empty() => {
            let (lemma, homonym) = lemma.split_once(':').expect("contains ':' checked");
            (Some(lemma.to_owned()), Some(homonym.to_owned()))
        }
        Some(lemma) => (Some(lemma.to_owned()), None),
    }
}

fn is_legacy_segment_type_pattern(pattern: &str) -> bool {
    pattern
        .chars()
        .next()
        .is_some_and(|ch| ch.is_ascii_lowercase() || matches!(ch, '_' | '.' | ':' | '%'))
}

fn segment_type_pattern_matches_tag(pattern: &str, tag: &str) -> bool {
    wildcard_pattern_matches(pattern, tag)
        || pattern
            .strip_suffix(":%")
            .is_some_and(|stripped| wildcard_pattern_matches(stripped, tag))
}

fn wildcard_pattern_matches(pattern: &str, tag: &str) -> bool {
    let pattern: Vec<char> = pattern.chars().collect();
    let tag: Vec<char> = tag.chars().collect();
    let mut memo = BTreeMap::new();
    wildcard_pattern_matches_from(&pattern, &tag, 0, 0, &mut memo)
}

fn wildcard_pattern_matches_from(
    pattern: &[char],
    tag: &[char],
    pattern_index: usize,
    tag_index: usize,
    memo: &mut BTreeMap<(usize, usize), bool>,
) -> bool {
    if let Some(result) = memo.get(&(pattern_index, tag_index)) {
        return *result;
    }
    let result = if pattern_index == pattern.len() {
        tag_index == tag.len()
    } else if pattern[pattern_index] == '%' {
        (tag_index..=tag.len()).any(|next_tag_index| {
            wildcard_pattern_matches_from(pattern, tag, pattern_index + 1, next_tag_index, memo)
        })
    } else if tag_index < tag.len()
        && (pattern[pattern_index] == '.' || pattern[pattern_index] == tag[tag_index])
    {
        wildcard_pattern_matches_from(pattern, tag, pattern_index + 1, tag_index + 1, memo)
    } else {
        false
    };
    memo.insert((pattern_index, tag_index), result);
    result
}

#[derive(Debug, Clone, PartialEq, Eq)]
enum SegmentRuleDefine {
    WithoutArg {
        name: String,
        value: String,
    },
    WithArg {
        name: String,
        arg: String,
        value: String,
    },
}

#[derive(Debug, Clone, PartialEq, Eq)]
enum SegmentRuleDefineValue {
    WithoutArg(String),
    WithArg { arg: String, value: String },
}

fn parse_segment_rule_define(
    line: &str,
    line_number: usize,
    input_name: &str,
) -> Result<SegmentRuleDefine> {
    let rest = line
        .strip_prefix("#define")
        .ok_or_else(|| BuilderError::new(format!("{input_name}:{line_number}: invalid #define")))?;
    let rest = rest.trim_start();
    let (name, mut cursor) = read_segment_rule_identifier(rest).ok_or_else(|| {
        BuilderError::new(format!(
            "{input_name}:{line_number}: #define must be followed by identifier"
        ))
    })?;

    if rest[cursor..].starts_with('(') {
        cursor += 1;
        let (arg, arg_len) = read_segment_rule_identifier(&rest[cursor..]).ok_or_else(|| {
            BuilderError::new(format!(
                "{input_name}:{line_number}: #define argument must be an identifier"
            ))
        })?;
        cursor += arg_len;
        let after_arg = rest[cursor..].trim_start();
        validate(
            after_arg.starts_with(')'),
            format!("{input_name}:{line_number}: #define argument list must end with ')'"),
        )?;
        let close_offset = rest.len() - after_arg.len();
        let value = rest[close_offset + 1..].to_owned();
        Ok(SegmentRuleDefine::WithArg { name, arg, value })
    } else {
        Ok(SegmentRuleDefine::WithoutArg {
            name,
            value: rest[cursor..].trim_start().to_owned(),
        })
    }
}

fn parse_segment_rule_ifdef(line: &str, line_number: usize, input_name: &str) -> Result<String> {
    let rest = line
        .strip_prefix("#ifdef")
        .ok_or_else(|| BuilderError::new(format!("{input_name}:{line_number}: invalid #ifdef")))?;
    let rest = rest.trim();
    validate(
        is_segment_rule_identifier(rest),
        format!("{input_name}:{line_number}: #ifdef must be followed by one identifier"),
    )?;
    Ok(rest.to_owned())
}

fn segment_rule_ifdefs_active(
    ifdefs_stack: &[(String, bool)],
    active_definitions: &BTreeSet<String>,
) -> bool {
    ifdefs_stack.iter().all(|(name, is_active)| {
        (active_definitions.contains(name) && *is_active)
            || (!active_definitions.contains(name) && !*is_active)
    })
}

fn process_segment_rule_line(
    line_number: usize,
    line: &str,
    defines: &BTreeMap<String, SegmentRuleDefineValue>,
    input_name: &str,
) -> Result<String> {
    if line.trim().is_empty() {
        return Ok(line.to_owned());
    }

    let mut current = line.to_owned();
    for _ in 0..128 {
        let processed = SegmentRuleLineProcessor::new(&current, line_number, defines, input_name)
            .parse_complete_rule()?;
        if processed.trim() == current.trim() {
            return Ok(current);
        }
        current = processed;
    }
    Err(BuilderError::new(format!(
        "{input_name}:{line_number}: recursive segmentation-rule define expansion did not stabilize"
    )))
}

struct SegmentRuleParser<'a, T> {
    line_number: usize,
    line: &'a str,
    cursor: usize,
    segment_types: &'a T,
    input_name: &'a str,
}

impl<'a, T> SegmentRuleParser<'a, T>
where
    T: SegmentTypeLookup,
{
    fn new(line_number: usize, line: &'a str, segment_types: &'a T, input_name: &'a str) -> Self {
        Self {
            line_number,
            line,
            cursor: 0,
            segment_types,
            input_name,
        }
    }

    fn parse_complete_rule(mut self) -> Result<SegmentRule> {
        let mut rule = self.parse_concat_rule(false)?;
        self.skip_whitespace();
        if self.remaining_starts_with_ignore_ascii_case("!weak") {
            self.cursor += "!weak".len();
            rule = rule.set_weak(true);
            self.skip_whitespace();
        }
        validate(
            self.cursor == self.line.len(),
            format!(
                "{}:{}: unexpected token in segmentation rule near {:?}",
                self.input_name,
                self.line_number,
                &self.line[self.cursor..]
            ),
        )?;
        Ok(rule)
    }

    fn parse_concat_rule(&mut self, stop_at_paren: bool) -> Result<SegmentRule> {
        let mut children = Vec::new();
        loop {
            self.skip_whitespace();
            if self.cursor == self.line.len()
                || (stop_at_paren && self.peek_char() == Some(')'))
                || self.remaining_starts_with_ignore_ascii_case("!weak")
            {
                break;
            }
            children.push(self.parse_one_of_rule()?);
        }
        validate(
            !children.is_empty(),
            format!(
                "{}:{}: empty segmentation rule",
                self.input_name, self.line_number
            ),
        )?;
        Ok(if children.len() == 1 {
            children.remove(0)
        } else {
            SegmentRule::concat(children, self.line_number)
        })
    }

    fn parse_one_of_rule(&mut self) -> Result<SegmentRule> {
        let mut children = vec![self.parse_unary_rule()?];
        loop {
            self.skip_whitespace();
            if self.peek_char() != Some('|') {
                break;
            }
            self.cursor += 1;
            children.push(self.parse_unary_rule()?);
        }
        Ok(if children.len() == 1 {
            children.remove(0)
        } else {
            SegmentRule::or(children, self.line_number)
        })
    }

    fn parse_unary_rule(&mut self) -> Result<SegmentRule> {
        let child = self.parse_atomic_rule()?;
        self.skip_whitespace();
        match self.peek_char() {
            Some('*') => {
                self.cursor += 1;
                Ok(SegmentRule::zero_or_more(child, self.line_number))
            }
            Some('+') => {
                self.cursor += 1;
                Ok(SegmentRule::concat(
                    vec![
                        child.clone(),
                        SegmentRule::zero_or_more(child, self.line_number),
                    ],
                    self.line_number,
                ))
            }
            Some('?') => {
                self.cursor += 1;
                Ok(SegmentRule::optional(child, self.line_number))
            }
            Some('{') => self.parse_quantified_rule(child),
            _ => Ok(child),
        }
    }

    fn parse_quantified_rule(&mut self, child: SegmentRule) -> Result<SegmentRule> {
        self.cursor += 1;
        self.skip_whitespace();
        let left = self.read_usize("quantity")?;
        self.skip_whitespace();
        match self.peek_char() {
            Some('}') => {
                self.cursor += 1;
                self.create_quant_rule_exact(child, left)
            }
            Some(',') => {
                self.cursor += 1;
                self.skip_whitespace();
                if self.peek_char() == Some('}') {
                    self.cursor += 1;
                    self.create_quant_rule_open(child, left)
                } else {
                    let right = self.read_usize("right quantity")?;
                    self.skip_whitespace();
                    validate(
                        self.peek_char() == Some('}'),
                        format!(
                            "{}:{}: quantity range must end with '}}'",
                            self.input_name, self.line_number
                        ),
                    )?;
                    self.cursor += 1;
                    self.create_quant_rule_range(child, left, right)
                }
            }
            _ => Err(BuilderError::new(format!(
                "{}:{}: invalid quantity expression",
                self.input_name, self.line_number
            ))),
        }
    }

    fn parse_atomic_rule(&mut self) -> Result<SegmentRule> {
        self.skip_whitespace();
        match self.peek_char() {
            Some('(') => {
                self.cursor += 1;
                let mut rule = self.parse_concat_rule(true)?;
                validate(
                    self.peek_char() == Some(')'),
                    format!(
                        "{}:{}: parenthesized rule must end with ')'",
                        self.input_name, self.line_number
                    ),
                )?;
                self.cursor += 1;
                self.skip_whitespace();
                if self.peek_char() == Some('>') {
                    self.cursor += 1;
                    rule.make_shift_orth_rule();
                }
                Ok(rule)
            }
            Some(ch) if is_rule_tag_start(ch) => {
                let segment_type = self.read_rule_tag().expect("tag start checked");
                self.skip_whitespace();
                let shift_orth = if self.peek_char() == Some('>') {
                    self.cursor += 1;
                    true
                } else {
                    false
                };
                let segment_type_num =
                    self.segment_types
                        .segment_type_num(&segment_type)
                        .map_err(|err| {
                            BuilderError::new(format!(
                                "{}:{}: {}",
                                self.input_name, self.line_number, err
                            ))
                        })?;
                Ok(SegmentRule::tag(
                    segment_type_num,
                    shift_orth,
                    segment_type,
                    self.line_number,
                ))
            }
            Some(ch) => Err(BuilderError::new(format!(
                "{}:{}: unexpected character {:?} in segmentation rule",
                self.input_name, self.line_number, ch
            ))),
            None => Err(BuilderError::new(format!(
                "{}:{}: unexpected end of segmentation rule",
                self.input_name, self.line_number
            ))),
        }
    }

    fn create_quant_rule_exact(&self, child: SegmentRule, quantity: usize) -> Result<SegmentRule> {
        validate(
            quantity > 0,
            format!(
                "{}:{}: {} - invalid quantity: {}",
                self.input_name, self.line_number, self.line, quantity
            ),
        )?;
        Ok(SegmentRule::concat(vec![child; quantity], self.line_number))
    }

    fn create_quant_rule_range(
        &self,
        child: SegmentRule,
        left: usize,
        right: usize,
    ) -> Result<SegmentRule> {
        validate(
            left <= right && (left, right) != (0, 0),
            format!(
                "{}:{}: {} - invalid quantities: {} {}",
                self.input_name, self.line_number, self.line, left, right
            ),
        )?;
        let mut children = Vec::new();
        if left == 0 {
            children.push(SegmentRule::optional(child.clone(), self.line_number));
            for quantity in 2..=right {
                children.push(self.create_quant_rule_exact(child.clone(), quantity)?);
            }
        } else {
            for quantity in left..=right {
                children.push(self.create_quant_rule_exact(child.clone(), quantity)?);
            }
        }
        Ok(SegmentRule::or(children, self.line_number))
    }

    fn create_quant_rule_open(&self, child: SegmentRule, quantity: usize) -> Result<SegmentRule> {
        validate(
            quantity > 0,
            format!(
                "{}:{}: {} - invalid quantity: {}",
                self.input_name, self.line_number, self.line, quantity
            ),
        )?;
        Ok(SegmentRule::concat(
            vec![
                self.create_quant_rule_exact(child.clone(), quantity)?,
                SegmentRule::zero_or_more(child, self.line_number),
            ],
            self.line_number,
        ))
    }

    fn skip_whitespace(&mut self) {
        while let Some(ch) = self.peek_char() {
            if ch.is_whitespace() {
                self.cursor += ch.len_utf8();
            } else {
                break;
            }
        }
    }

    fn read_usize(&mut self, field: &str) -> Result<usize> {
        let start = self.cursor;
        while let Some(ch) = self.peek_char() {
            if ch.is_ascii_digit() {
                self.cursor += ch.len_utf8();
            } else {
                break;
            }
        }
        validate(
            self.cursor > start,
            format!(
                "{}:{}: missing {field} in segmentation rule",
                self.input_name, self.line_number
            ),
        )?;
        self.line[start..self.cursor]
            .parse::<usize>()
            .map_err(|err| {
                BuilderError::new(format!(
                    "{}:{}: invalid {field}: {err}",
                    self.input_name, self.line_number
                ))
            })
    }

    fn peek_char(&self) -> Option<char> {
        self.line[self.cursor..].chars().next()
    }

    fn remaining_starts_with_ignore_ascii_case(&self, needle: &str) -> bool {
        self.line[self.cursor..]
            .get(..needle.len())
            .is_some_and(|prefix| prefix.eq_ignore_ascii_case(needle))
    }

    fn read_rule_tag(&mut self) -> Option<String> {
        let mut chars = self.line[self.cursor..].char_indices();
        let (_, first) = chars.next()?;
        if !is_rule_tag_start(first) {
            return None;
        }
        let mut end = first.len_utf8();
        for (index, ch) in chars {
            if is_rule_tag_body(ch) {
                end = index + ch.len_utf8();
            } else {
                break;
            }
        }
        let tag = self.line[self.cursor..self.cursor + end].to_owned();
        self.cursor += end;
        Some(tag)
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct SegmentRulesNfaState {
    transitions: BTreeMap<Option<SegmentRulesTransitionLabel>, BTreeSet<usize>>,
    final_state: bool,
    weak: bool,
    autogenerated: bool,
    rule_line_number: Option<usize>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct SegmentRulesNfa {
    states: Vec<SegmentRulesNfaState>,
    initial_state: usize,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SegmentRulesFsaLayout {
    pub dfs_order: Vec<usize>,
    pub offsets: Vec<usize>,
    pub reverse_offsets: Vec<usize>,
    pub total_size: usize,
}

impl SegmentRulesNfaState {
    fn initial() -> Self {
        Self {
            transitions: BTreeMap::new(),
            final_state: false,
            weak: false,
            autogenerated: false,
            rule_line_number: None,
        }
    }

    fn for_rule(rule: &SegmentRule) -> Self {
        Self {
            transitions: BTreeMap::new(),
            final_state: false,
            weak: false,
            autogenerated: rule.autogenerated,
            rule_line_number: Some(rule.line_number),
        }
    }

    fn final_for_rule(rule: &SegmentRule) -> Self {
        Self {
            transitions: BTreeMap::new(),
            final_state: true,
            weak: rule.weak,
            autogenerated: rule.autogenerated,
            rule_line_number: Some(rule.line_number),
        }
    }
}

impl SegmentRulesNfa {
    fn new() -> Self {
        Self {
            states: vec![SegmentRulesNfaState::initial()],
            initial_state: 0,
        }
    }

    fn add_state(&mut self, state: SegmentRulesNfaState) -> usize {
        let index = self.states.len();
        self.states.push(state);
        index
    }

    fn add_transition(
        &mut self,
        state_index: usize,
        label: Option<SegmentRulesTransitionLabel>,
        target: usize,
    ) {
        self.states[state_index]
            .transitions
            .entry(label)
            .or_default()
            .insert(target);
    }

    fn closure_from(&self, state_index: usize) -> BTreeSet<usize> {
        let mut visited = BTreeSet::new();
        self.add_closure(state_index, &mut visited);
        visited
    }

    fn add_closure(&self, state_index: usize, visited: &mut BTreeSet<usize>) {
        if !visited.insert(state_index) {
            return;
        }
        if let Some(next_states) = self.states[state_index].transitions.get(&None) {
            for &next_state in next_states {
                self.add_closure(next_state, visited);
            }
        }
    }

    fn grouped_output_by_labels(
        &self,
        nfa_states: &BTreeSet<usize>,
    ) -> Vec<(SegmentRulesTransitionLabel, BTreeSet<usize>)> {
        let mut ordered_states: Vec<usize> = nfa_states.iter().copied().collect();
        ordered_states.sort_by(|left, right| {
            self.states[*right]
                .rule_line_number
                .unwrap_or_default()
                .cmp(&self.states[*left].rule_line_number.unwrap_or_default())
                .then(left.cmp(right))
        });

        let mut grouped: Vec<(SegmentRulesTransitionLabel, BTreeSet<usize>)> = Vec::new();
        for state_index in ordered_states {
            for (label, next_states) in &self.states[state_index].transitions {
                let Some(label) = *label else {
                    continue;
                };
                let position = grouped
                    .iter()
                    .position(|(existing_label, _targets)| *existing_label == label);
                let targets = if let Some(position) = position {
                    &mut grouped[position].1
                } else {
                    grouped.push((label, BTreeSet::new()));
                    &mut grouped.last_mut().expect("just pushed label group").1
                };
                for &next_state in next_states {
                    targets.extend(self.closure_from(next_state));
                }
            }
        }
        grouped
    }

    fn convert_to_dfa(&self, input_name: &str) -> Result<SegmentRulesFsa> {
        let start_states = self.closure_from(self.initial_state);
        validate(
            !start_states
                .iter()
                .any(|state_index| self.states[*state_index].final_state),
            "initial segmentation-rule NFA closure must not be accepting",
        )?;

        let mut dfa = SegmentRulesFsa {
            states: Vec::new(),
            initial_state: 0,
        };
        let mut nfa_subset_to_dfa_state = BTreeMap::new();
        let initial_state = self.convert_subset_to_dfa_state(
            &start_states,
            &mut dfa,
            &mut nfa_subset_to_dfa_state,
            input_name,
        )?;
        dfa.initial_state = initial_state;
        Ok(dfa)
    }

    fn convert_subset_to_dfa_state(
        &self,
        nfa_states: &BTreeSet<usize>,
        dfa: &mut SegmentRulesFsa,
        nfa_subset_to_dfa_state: &mut BTreeMap<BTreeSet<usize>, usize>,
        input_name: &str,
    ) -> Result<usize> {
        if let Some(state_index) = nfa_subset_to_dfa_state.get(nfa_states) {
            return Ok(*state_index);
        }

        let (accepting, weak) = self.dfa_state_acceptance(nfa_states, input_name)?;
        let state_index = dfa.states.len();
        nfa_subset_to_dfa_state.insert(nfa_states.clone(), state_index);
        dfa.states.push(SegmentRulesState {
            accepting,
            weak,
            transitions: BTreeMap::new(),
            transition_order: Vec::new(),
        });

        for (label, next_nfa_states) in self.grouped_output_by_labels(nfa_states) {
            let next_dfa_state = self.convert_subset_to_dfa_state(
                &next_nfa_states,
                dfa,
                nfa_subset_to_dfa_state,
                input_name,
            )?;
            if !dfa.states[state_index].transitions.contains_key(&label) {
                dfa.states[state_index].transition_order.push(label);
            }
            dfa.states[state_index]
                .transitions
                .insert(label, next_dfa_state);
        }
        Ok(state_index)
    }

    fn dfa_state_acceptance(
        &self,
        nfa_states: &BTreeSet<usize>,
        input_name: &str,
    ) -> Result<(bool, bool)> {
        let weak_hits: Vec<(bool, usize)> = nfa_states
            .iter()
            .filter_map(|state_index| {
                let state = &self.states[*state_index];
                (state.final_state && !state.autogenerated).then(|| {
                    (
                        state.weak,
                        state
                            .rule_line_number
                            .expect("final rule state has source line"),
                    )
                })
            })
            .collect();

        if weak_hits.iter().any(|(weak, _line)| *weak)
            && !weak_hits.iter().all(|(weak, _line)| *weak)
        {
            let weak_line = weak_hits
                .iter()
                .find_map(|(weak, line)| (*weak).then_some(*line))
                .expect("weak hit exists");
            let non_weak_line = weak_hits
                .iter()
                .find_map(|(weak, line)| (!*weak).then_some(*line))
                .expect("non-weak hit exists");
            return Err(BuilderError::new(format!(
                "{input_name}:{weak_line} - conflicts with rule at line {non_weak_line}. Segmentation for some chunks can be both weak and non-weak which is illegal."
            )));
        }

        let accepting = nfa_states
            .iter()
            .any(|state_index| self.states[*state_index].final_state);
        let weak = nfa_states.iter().any(|state_index| {
            let state = &self.states[*state_index];
            state.final_state && state.weak && !state.autogenerated
        });
        Ok((accepting, weak))
    }
}

struct SegmentRuleLineProcessor<'a> {
    line: &'a str,
    cursor: usize,
    line_number: usize,
    defines: &'a BTreeMap<String, SegmentRuleDefineValue>,
    input_name: &'a str,
}

impl<'a> SegmentRuleLineProcessor<'a> {
    fn new(
        line: &'a str,
        line_number: usize,
        defines: &'a BTreeMap<String, SegmentRuleDefineValue>,
        input_name: &'a str,
    ) -> Self {
        Self {
            line,
            cursor: 0,
            line_number,
            defines,
            input_name,
        }
    }

    fn parse_complete_rule(mut self) -> Result<String> {
        let rule = self.parse_rule(false)?;
        self.skip_whitespace();
        validate(
            self.cursor == self.line.len(),
            format!(
                "{}:{}: unexpected token in segmentation rule near {:?}",
                self.input_name,
                self.line_number,
                &self.line[self.cursor..]
            ),
        )?;
        Ok(rule)
    }

    fn parse_rule(&mut self, stop_at_paren: bool) -> Result<String> {
        let mut tokens = Vec::new();
        loop {
            self.skip_whitespace();
            if self.cursor == self.line.len() || (stop_at_paren && self.peek_char() == Some(')')) {
                break;
            }
            tokens.push(self.parse_token()?);
        }
        Ok(tokens.join(" "))
    }

    fn parse_token(&mut self) -> Result<String> {
        if self.line[self.cursor..]
            .to_ascii_lowercase()
            .starts_with("!weak")
        {
            self.cursor += "!weak".len();
            return Ok("!weak".to_owned());
        }

        match self.peek_char() {
            Some('(') => {
                self.cursor += 1;
                let inner = self.parse_rule(true)?;
                validate(
                    self.peek_char() == Some(')'),
                    format!(
                        "{}:{}: unterminated parenthesized segmentation rule",
                        self.input_name, self.line_number
                    ),
                )?;
                self.cursor += 1;
                Ok(format!("( {inner} )"))
            }
            Some(ch) if is_segment_rule_operator(ch) => Ok(self.read_operator_word()),
            Some(ch) if is_segment_rule_identifier_start(ch) => {
                let name = self.read_identifier().expect("identifier start checked");
                self.skip_whitespace();
                if self.peek_char() == Some('(') {
                    self.cursor += 1;
                    let substitute_value = self.parse_rule(true)?;
                    validate(
                        self.peek_char() == Some(')'),
                        format!(
                            "{}:{}: unterminated define invocation",
                            self.input_name, self.line_number
                        ),
                    )?;
                    self.cursor += 1;
                    Ok(self.substitute_arg_define(&name, &substitute_value))
                } else {
                    Ok(self.substitute_non_arg_define(&name))
                }
            }
            Some(ch) => Err(BuilderError::new(format!(
                "{}:{}: unexpected character {:?} in segmentation rule",
                self.input_name, self.line_number, ch
            ))),
            None => Err(BuilderError::new(format!(
                "{}:{}: unexpected end of segmentation rule",
                self.input_name, self.line_number
            ))),
        }
    }

    fn substitute_arg_define(&self, name: &str, substitute_value: &str) -> String {
        match self.defines.get(name) {
            Some(SegmentRuleDefineValue::WithArg { arg, value }) => {
                replace_ascii_word(value, arg, substitute_value)
            }
            Some(SegmentRuleDefineValue::WithoutArg(value)) => {
                format!("{value} ( {substitute_value} )")
            }
            None => format!("{name} ( {substitute_value} )"),
        }
    }

    fn substitute_non_arg_define(&self, name: &str) -> String {
        match self.defines.get(name) {
            Some(SegmentRuleDefineValue::WithoutArg(value)) => value.clone(),
            _ => name.to_owned(),
        }
    }

    fn skip_whitespace(&mut self) {
        while let Some(ch) = self.peek_char() {
            if ch.is_whitespace() {
                self.cursor += ch.len_utf8();
            } else {
                break;
            }
        }
    }

    fn peek_char(&self) -> Option<char> {
        self.line[self.cursor..].chars().next()
    }

    fn read_identifier(&mut self) -> Option<String> {
        let (identifier, len) = read_segment_rule_identifier(&self.line[self.cursor..])?;
        self.cursor += len;
        Some(identifier)
    }

    fn read_operator_word(&mut self) -> String {
        let start = self.cursor;
        while let Some(ch) = self.peek_char() {
            if is_segment_rule_operator(ch) {
                self.cursor += ch.len_utf8();
            } else {
                break;
            }
        }
        self.line[start..self.cursor].to_owned()
    }
}

fn read_segment_rule_identifier(input: &str) -> Option<(String, usize)> {
    let mut chars = input.char_indices();
    let (_, first) = chars.next()?;
    if !is_segment_rule_identifier_start(first) {
        return None;
    }
    let mut end = first.len_utf8();
    for (index, ch) in chars {
        if is_segment_rule_identifier_body(ch) {
            end = index + ch.len_utf8();
        } else {
            break;
        }
    }
    Some((input[..end].to_owned(), end))
}

fn is_segment_rule_identifier(input: &str) -> bool {
    read_segment_rule_identifier(input)
        .map(|(_identifier, len)| len == input.len())
        .unwrap_or(false)
}

fn is_segment_rule_identifier_start(ch: char) -> bool {
    ch.is_ascii_alphabetic()
}

fn is_segment_rule_identifier_body(ch: char) -> bool {
    ch.is_ascii_alphanumeric() || matches!(ch, '_' | '>' | '*' | '+' | '{' | '}' | ',')
}

fn is_segment_rule_operator(ch: char) -> bool {
    matches!(ch, '*' | '|' | '+' | '?' | '>')
}

fn is_rule_tag_start(ch: char) -> bool {
    is_rule_tag_body(ch)
}

fn is_rule_tag_body(ch: char) -> bool {
    ch.is_ascii_alphanumeric() || ch == '_'
}

pub(crate) fn replace_ascii_word(input: &str, word: &str, replacement: &str) -> String {
    if word.is_empty() {
        return input.to_owned();
    }
    let mut out = String::with_capacity(input.len());
    let mut cursor = 0usize;
    while let Some(relative) = input[cursor..].find(word) {
        let start = cursor + relative;
        let end = start + word.len();
        if is_ascii_word_start_boundary(input, start) && is_ascii_word_end_boundary(input, end) {
            out.push_str(&input[cursor..start]);
            out.push_str(replacement);
            cursor = end;
        } else {
            out.push_str(&input[cursor..end]);
            cursor = end;
        }
    }
    out.push_str(&input[cursor..]);
    out
}

fn is_ascii_word_start_boundary(input: &str, index: usize) -> bool {
    if index == 0 {
        true
    } else {
        !is_ascii_regex_word_byte(input.as_bytes()[index - 1])
    }
}

fn is_ascii_word_end_boundary(input: &str, index: usize) -> bool {
    if index == input.len() {
        true
    } else {
        !is_ascii_regex_word_byte(input.as_bytes()[index])
    }
}

fn is_ascii_regex_word_byte(byte: u8) -> bool {
    byte.is_ascii_alphanumeric() || byte == b'_'
}
