use std::collections::{BTreeMap, BTreeSet};

use super::rule::SegmentRule;
use super::types::{SegmentRulesFsa, SegmentRulesState, SegmentRulesTransitionLabel};
use crate::error::{validate, BuilderError, Result};

pub fn build_segment_rules_fsa<'a, I>(rules: I, input_name: &str) -> Result<SegmentRulesFsa>
where
    I: IntoIterator<Item = &'a SegmentRule>,
{
    let mut nfa = SegmentRulesNfa::new();
    for rule in rules {
        rule.add_to_segment_rules_nfa(&mut nfa)?;
    }
    nfa.convert_to_dfa(input_name)
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub(super) struct SegmentRulesNfaState {
    transitions: BTreeMap<Option<SegmentRulesTransitionLabel>, BTreeSet<usize>>,
    final_state: bool,
    weak: bool,
    autogenerated: bool,
    rule_line_number: Option<usize>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub(super) struct SegmentRulesNfa {
    states: Vec<SegmentRulesNfaState>,
    pub(super) initial_state: usize,
}

impl SegmentRulesNfaState {
    fn initial() -> Self {
        Self {
            transitions: BTreeMap::new(),
            final_state: false,
            weak: false,
            autogenerated: false,
            rule_line_number: None,
        }
    }

    pub(super) fn for_rule(rule: &SegmentRule) -> Self {
        Self {
            transitions: BTreeMap::new(),
            final_state: false,
            weak: false,
            autogenerated: rule.autogenerated,
            rule_line_number: Some(rule.line_number),
        }
    }

    pub(super) fn final_for_rule(rule: &SegmentRule) -> Self {
        Self {
            transitions: BTreeMap::new(),
            final_state: true,
            weak: rule.weak,
            autogenerated: rule.autogenerated,
            rule_line_number: Some(rule.line_number),
        }
    }
}

impl SegmentRulesNfa {
    fn new() -> Self {
        Self {
            states: vec![SegmentRulesNfaState::initial()],
            initial_state: 0,
        }
    }

    pub(super) fn add_state(&mut self, state: SegmentRulesNfaState) -> usize {
        let index = self.states.len();
        self.states.push(state);
        index
    }

    pub(super) fn add_transition(
        &mut self,
        state_index: usize,
        label: Option<SegmentRulesTransitionLabel>,
        target: usize,
    ) {
        self.states[state_index]
            .transitions
            .entry(label)
            .or_default()
            .insert(target);
    }

    fn closure_from(&self, state_index: usize) -> BTreeSet<usize> {
        let mut visited = BTreeSet::new();
        self.add_closure(state_index, &mut visited);
        visited
    }

    fn add_closure(&self, state_index: usize, visited: &mut BTreeSet<usize>) {
        if !visited.insert(state_index) {
            return;
        }
        if let Some(next_states) = self.states[state_index].transitions.get(&None) {
            for &next_state in next_states {
                self.add_closure(next_state, visited);
            }
        }
    }

    fn grouped_output_by_labels(
        &self,
        nfa_states: &BTreeSet<usize>,
    ) -> Vec<(SegmentRulesTransitionLabel, BTreeSet<usize>)> {
        let mut ordered_states: Vec<usize> = nfa_states.iter().copied().collect();
        ordered_states.sort_by(|left, right| {
            self.states[*right]
                .rule_line_number
                .unwrap_or_default()
                .cmp(&self.states[*left].rule_line_number.unwrap_or_default())
                .then(left.cmp(right))
        });

        let mut grouped: Vec<(SegmentRulesTransitionLabel, BTreeSet<usize>)> = Vec::new();
        for state_index in ordered_states {
            for (label, next_states) in &self.states[state_index].transitions {
                let Some(label) = *label else {
                    continue;
                };
                let position = grouped
                    .iter()
                    .position(|(existing_label, _targets)| *existing_label == label);
                let targets = if let Some(position) = position {
                    &mut grouped[position].1
                } else {
                    grouped.push((label, BTreeSet::new()));
                    &mut grouped.last_mut().expect("just pushed label group").1
                };
                for &next_state in next_states {
                    targets.extend(self.closure_from(next_state));
                }
            }
        }
        grouped
    }

    fn convert_to_dfa(&self, input_name: &str) -> Result<SegmentRulesFsa> {
        let start_states = self.closure_from(self.initial_state);
        validate(
            !start_states
                .iter()
                .any(|state_index| self.states[*state_index].final_state),
            "initial segmentation-rule NFA closure must not be accepting",
        )?;

        let mut dfa = SegmentRulesFsa {
            states: Vec::new(),
            initial_state: 0,
        };
        let mut nfa_subset_to_dfa_state = BTreeMap::new();
        let initial_state = self.convert_subset_to_dfa_state(
            &start_states,
            &mut dfa,
            &mut nfa_subset_to_dfa_state,
            input_name,
        )?;
        dfa.initial_state = initial_state;
        Ok(dfa)
    }

    fn convert_subset_to_dfa_state(
        &self,
        nfa_states: &BTreeSet<usize>,
        dfa: &mut SegmentRulesFsa,
        nfa_subset_to_dfa_state: &mut BTreeMap<BTreeSet<usize>, usize>,
        input_name: &str,
    ) -> Result<usize> {
        if let Some(state_index) = nfa_subset_to_dfa_state.get(nfa_states) {
            return Ok(*state_index);
        }

        let (accepting, weak) = self.dfa_state_acceptance(nfa_states, input_name)?;
        let state_index = dfa.states.len();
        nfa_subset_to_dfa_state.insert(nfa_states.clone(), state_index);
        dfa.states.push(SegmentRulesState {
            accepting,
            weak,
            transitions: BTreeMap::new(),
            transition_order: Vec::new(),
        });

        for (label, next_nfa_states) in self.grouped_output_by_labels(nfa_states) {
            let next_dfa_state = self.convert_subset_to_dfa_state(
                &next_nfa_states,
                dfa,
                nfa_subset_to_dfa_state,
                input_name,
            )?;
            if !dfa.states[state_index].transitions.contains_key(&label) {
                dfa.states[state_index].transition_order.push(label);
            }
            dfa.states[state_index]
                .transitions
                .insert(label, next_dfa_state);
        }
        Ok(state_index)
    }

    fn dfa_state_acceptance(
        &self,
        nfa_states: &BTreeSet<usize>,
        input_name: &str,
    ) -> Result<(bool, bool)> {
        let weak_hits: Vec<(bool, usize)> = nfa_states
            .iter()
            .filter_map(|state_index| {
                let state = &self.states[*state_index];
                (state.final_state && !state.autogenerated).then(|| {
                    (
                        state.weak,
                        state
                            .rule_line_number
                            .expect("final rule state has source line"),
                    )
                })
            })
            .collect();

        if weak_hits.iter().any(|(weak, _line)| *weak)
            && !weak_hits.iter().all(|(weak, _line)| *weak)
        {
            let weak_line = weak_hits
                .iter()
                .find_map(|(weak, line)| (*weak).then_some(*line))
                .expect("weak hit exists");
            let non_weak_line = weak_hits
                .iter()
                .find_map(|(weak, line)| (!*weak).then_some(*line))
                .expect("non-weak hit exists");
            return Err(BuilderError::new(format!(
                "{input_name}:{weak_line} - conflicts with rule at line {non_weak_line}. Segmentation for some chunks can be both weak and non-weak which is illegal."
            )));
        }

        let accepting = nfa_states
            .iter()
            .any(|state_index| self.states[*state_index].final_state);
        let weak = nfa_states.iter().any(|state_index| {
            let state = &self.states[*state_index];
            state.final_state && state.weak && !state.autogenerated
        });
        Ok((accepting, weak))
    }
}
