use std::collections::{BTreeMap, BTreeSet};

use super::parser::parse_segment_rule_line;
use super::preprocess::{is_ascii_word, preprocess_segment_rules};
use super::resolver::SegmentTypeResolver;
use super::rule::SegmentRule;
use super::serialization::{serialize_segment_rules_fsa, serialize_segmentation_rules_data};
use super::types::{ParsedSegmentRules, SegmentRulesFsaVariantData, SegmentRulesTarget};
use crate::constants::QualifierSet;
use crate::error::{validate, BuilderError, Result};
use crate::tagset::TagsetRulesLookup;

pub fn parse_segmentation_rules_from_str(
    input_name: &str,
    input: &str,
    target: SegmentRulesTarget,
) -> Result<ParsedSegmentRules> {
    let config = SegmentRulesConfigFile::parse(
        input_name,
        input,
        [
            "options",
            "combinations",
            "tags",
            "lexemes",
            "segment types",
            "separator chars",
        ],
    )?;
    let segment_types = parse_segment_types_section(&config)?;
    parse_segmentation_rules_config(input_name, &config, target, segment_types, None)
}

pub fn parse_segmentation_rules_with_tagset_from_str<T>(
    input_name: &str,
    input: &str,
    target: SegmentRulesTarget,
    tagset: &T,
    names_map: &BTreeMap<String, usize>,
    labels_map: &BTreeMap<QualifierSet, usize>,
) -> Result<ParsedSegmentRules>
where
    T: TagsetRulesLookup,
{
    let config = SegmentRulesConfigFile::parse(
        input_name,
        input,
        [
            "options",
            "combinations",
            "tags",
            "lexemes",
            "segment types",
            "separator chars",
        ],
    )?;
    let segment_types = parse_segment_types_section(&config)?;
    let segment_type_resolver = SegmentTypeResolver::from_config(
        &config,
        segment_types.clone(),
        tagset,
        names_map,
        labels_map,
    )?;
    parse_segmentation_rules_config(
        input_name,
        &config,
        target,
        segment_types,
        Some(segment_type_resolver),
    )
}

fn parse_segmentation_rules_config(
    input_name: &str,
    config: &SegmentRulesConfigFile,
    target: SegmentRulesTarget,
    segment_types: Vec<String>,
    segment_type_resolver: Option<SegmentTypeResolver>,
) -> Result<ParsedSegmentRules> {
    let option_definitions = parse_segment_rules_options(config)?;
    let segment_type_nums: BTreeMap<String, usize> = segment_types
        .iter()
        .enumerate()
        .map(|(index, segment_type)| (segment_type.clone(), index))
        .collect();
    let separators = if target == SegmentRulesTarget::Analyzer {
        parse_separator_chars_section(config)?
    } else {
        Vec::new()
    };

    let definitions_to_option_keys = definitions_to_option_keys(&option_definitions);
    let option_combinations = segment_rules_option_combinations(&option_definitions);
    let combination_lines = config.lines_in_section("combinations", false)?;
    let mut rules_by_options = Vec::new();

    for active_definitions in option_combinations {
        let options =
            active_definitions_to_options(&active_definitions, &definitions_to_option_keys)?;
        let preprocessed = preprocess_segment_rules(
            combination_lines.iter().cloned(),
            &active_definitions,
            input_name,
        )?;
        let mut rules = Vec::new();
        for (line_number, line) in preprocessed {
            if line.starts_with('#') {
                continue;
            }
            let mut rule =
                parse_segment_rule_line(line_number, &line, &segment_type_nums, input_name)?;
            if rule.allows_empty_sequence() {
                return Err(BuilderError::new(format!(
                    "{input_name}:{line_number} - This rule allows empty segments sequence to be accepted"
                )));
            }
            rule.validate_segment_rule(input_name)?;
            if target == SegmentRulesTarget::Generator {
                let mut additional_rules = rule.additional_atomic_rules_for_generator();
                for additional_rule in &mut additional_rules {
                    additional_rule.autogenerated = true;
                }
                rules.extend(additional_rules);
                rule = rule.transform_to_generator_version();
            }
            if !rule.is_sink_rule() {
                rules.push(rule);
            }
        }
        rules_by_options.push((options, rules));
    }

    let shift_magic = apply_shift_orth_magic(&segment_types, &mut rules_by_options);
    let mut variants = Vec::with_capacity(rules_by_options.len());
    for (options, rules) in &rules_by_options {
        variants.push(SegmentRulesFsaVariantData {
            options: options.clone(),
            fsa: serialize_segment_rules_fsa(rules.iter(), input_name)?,
        });
    }
    let default_options = variants
        .first()
        .map(|variant| variant.options.clone())
        .ok_or_else(|| BuilderError::new("Too many segmentation rules variants"))?;
    let segmentation_rules_data =
        serialize_segmentation_rules_data(separators.iter().copied(), &variants, &default_options)?;

    Ok(ParsedSegmentRules {
        segment_types,
        segment_type_resolver: segment_type_resolver.map(|resolver| {
            resolver.with_shift_magic(
                shift_magic.replace_lemma_with_orth.clone(),
                shift_magic.shift_orth_extra_segment_types.clone(),
            )
        }),
        separators,
        variants,
        default_options,
        segmentation_rules_data,
        replace_lemma_with_orth: shift_magic.replace_lemma_with_orth,
        shift_orth_extra_segment_types: shift_magic.shift_orth_extra_segment_types,
        additional_segment_type_names: shift_magic.additional_segment_type_names,
    })
}

pub(super) struct SegmentRulesConfigFile {
    pub(super) input_name: String,
    section_names: BTreeSet<String>,
    section_lines: BTreeMap<String, Vec<(usize, String)>>,
}

#[derive(Debug, Clone, PartialEq, Eq, Default)]
struct ShiftOrthMagicData {
    replace_lemma_with_orth: BTreeSet<usize>,
    shift_orth_extra_segment_types: BTreeMap<usize, usize>,
    additional_segment_type_names: BTreeMap<usize, String>,
}

impl SegmentRulesConfigFile {
    fn parse<I, S>(input_name: &str, input: &str, section_names: I) -> Result<Self>
    where
        I: IntoIterator<Item = S>,
        S: AsRef<str>,
    {
        let section_names: BTreeSet<String> = section_names
            .into_iter()
            .map(|section_name| section_name.as_ref().to_owned())
            .collect();
        let mut section_lines = BTreeMap::new();
        let mut current_section: Option<String> = None;

        for (line_index, raw_line) in input.lines().enumerate() {
            let line_number = line_index + 1;
            if let Some(section_name) = segment_rules_header_value(raw_line) {
                validate(
                    section_names.contains(&section_name),
                    format!("{input_name}:{line_number} - Invalid section: {section_name}"),
                )?;
                validate(
                    !section_lines.contains_key(&section_name),
                    format!("{input_name}:{line_number} - Duplicate section: {section_name}"),
                )?;
                section_lines.insert(section_name.clone(), Vec::new());
                current_section = Some(section_name);
            } else {
                let line = raw_line.trim();
                if line.is_empty() {
                    continue;
                }
                let Some(section_name) = current_section.as_ref() else {
                    if line.starts_with('#') {
                        continue;
                    }
                    return Err(BuilderError::new(format!(
                        "{input_name}:{line_number} - Text outside of any section"
                    )));
                };
                section_lines
                    .get_mut(section_name)
                    .expect("current section was inserted")
                    .push((line_number, line.to_owned()));
            }
        }

        Ok(Self {
            input_name: input_name.to_owned(),
            section_names,
            section_lines,
        })
    }

    pub(super) fn lines_in_section(
        &self,
        section_name: &str,
        ignore_comments: bool,
    ) -> Result<Vec<(usize, String)>> {
        validate(
            self.section_names.contains(section_name),
            format!("invalid known section request: {section_name}"),
        )?;
        let lines = self.section_lines.get(section_name).ok_or_else(|| {
            BuilderError::new(format!(
                "{} - Missing section: \"{}\"",
                self.input_name, section_name
            ))
        })?;
        Ok(lines
            .iter()
            .filter(|(_line_number, line)| !ignore_comments || !line.starts_with('#'))
            .cloned()
            .collect())
    }
}

fn segment_rules_header_value(line: &str) -> Option<String> {
    let line = line.trim_start();
    let rest = line.strip_prefix('[')?;
    let end = rest.find(']')?;
    Some(rest[..end].to_owned())
}

fn parse_segment_rules_options(
    config: &SegmentRulesConfigFile,
) -> Result<Vec<(String, Vec<String>)>> {
    let mut options = Vec::new();
    for (line_number, line) in config.lines_in_section("options", true)? {
        let (key, values) = line.split_once('=').ok_or_else(|| {
            BuilderError::new(format!(
                "{}:{line_number} - Error in [options] section: missing '='",
                config.input_name
            ))
        })?;
        let key = key.trim();
        validate(
            is_ascii_word(key),
            format!(
                "{}:{line_number} - Error in [options] section: invalid option key: {key}",
                config.input_name
            ),
        )?;
        let values: Vec<String> = values.split_whitespace().map(str::to_owned).collect();
        validate(
            !values.is_empty() && values.iter().all(|value| is_ascii_word(value)),
            format!(
                "{}:{line_number} - Error in [options] section: invalid option values",
                config.input_name
            ),
        )?;
        options.push((key.to_owned(), values));
    }
    Ok(options)
}

fn parse_segment_types_section(config: &SegmentRulesConfigFile) -> Result<Vec<String>> {
    let mut segment_types = Vec::new();
    for (line_number, line) in config.lines_in_section("segment types", true)? {
        validate(
            is_ascii_word(&line),
            format!(
                "{}:{line_number} - Segment type must be a single word",
                config.input_name
            ),
        )?;
        validate(
            !segment_types.contains(&line),
            format!(
                "{}:{line_number} - Segment type already defined: \"{}\"",
                config.input_name, line
            ),
        )?;
        segment_types.push(line);
    }
    Ok(segment_types)
}

fn parse_separator_chars_section(config: &SegmentRulesConfigFile) -> Result<Vec<u32>> {
    let mut separators = Vec::new();
    for (line_number, line) in config.lines_in_section("separator chars", true)? {
        let separator = line.parse::<u32>().map_err(|err| {
            BuilderError::new(format!("{}:{line_number} - {err}", config.input_name))
        })?;
        separators.push(separator);
    }
    Ok(separators)
}

fn definitions_to_option_keys(
    option_definitions: &[(String, Vec<String>)],
) -> BTreeMap<String, String> {
    let mut definitions_to_option_keys = BTreeMap::new();
    for (key, definitions) in option_definitions {
        for definition in definitions {
            definitions_to_option_keys.insert(definition.clone(), key.clone());
        }
    }
    definitions_to_option_keys
}

fn segment_rules_option_combinations(
    option_definitions: &[(String, Vec<String>)],
) -> Vec<Vec<String>> {
    let mut combinations = vec![Vec::new()];
    for (_key, definitions) in option_definitions {
        let mut next = Vec::new();
        for combination in &combinations {
            for definition in definitions {
                let mut combination = combination.clone();
                combination.push(definition.clone());
                next.push(combination);
            }
        }
        combinations = next;
    }
    combinations
}

fn active_definitions_to_options(
    active_definitions: &[String],
    definitions_to_option_keys: &BTreeMap<String, String>,
) -> Result<BTreeMap<String, String>> {
    let mut options = BTreeMap::new();
    for definition in active_definitions {
        let key = definitions_to_option_keys.get(definition).ok_or_else(|| {
            BuilderError::new(format!("missing option key for definition {definition}"))
        })?;
        options.insert(key.clone(), definition.clone());
    }
    Ok(options)
}

fn apply_shift_orth_magic(
    segment_types: &[String],
    rules_by_options: &mut [(BTreeMap<String, String>, Vec<SegmentRule>)],
) -> ShiftOrthMagicData {
    let mut shift_orth_segment_types = BTreeSet::new();
    let mut non_shift_orth_segment_types = BTreeSet::new();

    for (_options, rules) in rules_by_options.iter() {
        for rule in rules {
            let mut atoms = Vec::new();
            rule.collect_atomic_rule_info(&mut atoms);
            for atom in atoms {
                if atom.shift_orth {
                    shift_orth_segment_types.insert(atom.segment_type);
                } else {
                    non_shift_orth_segment_types.insert(atom.segment_type);
                }
            }
        }
    }

    let mut result = ShiftOrthMagicData::default();
    let mut next_new_segment_type_num = segment_types.len();
    for (segment_type_num, segment_type) in segment_types.iter().enumerate() {
        if shift_orth_segment_types.contains(segment_type)
            && non_shift_orth_segment_types.contains(segment_type)
        {
            result
                .shift_orth_extra_segment_types
                .insert(segment_type_num, next_new_segment_type_num);
            result
                .additional_segment_type_names
                .insert(next_new_segment_type_num, format!("{segment_type}>"));
            next_new_segment_type_num += 1;
        } else if shift_orth_segment_types.contains(segment_type) {
            result.replace_lemma_with_orth.insert(segment_type_num);
        }
    }

    for (_options, rules) in rules_by_options {
        for rule in rules {
            rule.remap_shift_orth_segment_types(&result.shift_orth_extra_segment_types);
        }
    }

    result
}
