use std::collections::BTreeMap;
use std::fmt;

use super::automaton::{SegmentRulesNfa, SegmentRulesNfaState};
use super::types::SegmentRulesTransitionLabel;
use crate::error::{BuilderError, Result};

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SegmentRule {
    kind: SegmentRuleKind,
    pub(super) line_number: usize,
    pub(super) weak: bool,
    pub(super) autogenerated: bool,
}

#[derive(Debug, Clone, PartialEq, Eq)]
enum SegmentRuleKind {
    Tag {
        segment_type_num: usize,
        shift_orth: bool,
        segment_type: String,
    },
    Concat(Vec<SegmentRule>),
    Or(Vec<SegmentRule>),
    ZeroOrMore(Box<SegmentRule>),
    Optional(Box<SegmentRule>),
    Sink,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub(super) struct SegmentRuleAtom {
    pub(super) segment_type_num: usize,
    pub(super) shift_orth: bool,
    pub(super) segment_type: String,
}

impl SegmentRule {
    pub(super) fn tag(
        segment_type_num: usize,
        shift_orth: bool,
        segment_type: impl Into<String>,
        line_number: usize,
    ) -> Self {
        Self {
            kind: SegmentRuleKind::Tag {
                segment_type_num,
                shift_orth,
                segment_type: segment_type.into(),
            },
            line_number,
            weak: false,
            autogenerated: false,
        }
    }

    pub(super) fn concat(children: Vec<Self>, line_number: usize) -> Self {
        debug_assert!(!children.is_empty());
        Self {
            kind: SegmentRuleKind::Concat(children),
            line_number,
            weak: false,
            autogenerated: false,
        }
    }

    pub(super) fn or(children: Vec<Self>, line_number: usize) -> Self {
        debug_assert!(!children.is_empty());
        Self {
            kind: SegmentRuleKind::Or(children),
            line_number,
            weak: false,
            autogenerated: false,
        }
    }

    pub(super) fn zero_or_more(child: Self, line_number: usize) -> Self {
        Self {
            kind: SegmentRuleKind::ZeroOrMore(Box::new(child)),
            line_number,
            weak: false,
            autogenerated: false,
        }
    }

    pub(super) fn optional(child: Self, line_number: usize) -> Self {
        Self {
            kind: SegmentRuleKind::Optional(Box::new(child)),
            line_number,
            weak: false,
            autogenerated: false,
        }
    }

    fn sink() -> Self {
        Self {
            kind: SegmentRuleKind::Sink,
            line_number: 0,
            weak: false,
            autogenerated: false,
        }
    }

    pub fn is_weak(&self) -> bool {
        self.weak
    }

    pub fn set_weak(mut self, weak: bool) -> Self {
        self.weak = weak;
        self
    }

    pub fn line_number(&self) -> usize {
        self.line_number
    }

    pub fn is_sink_rule(&self) -> bool {
        matches!(self.kind, SegmentRuleKind::Sink)
    }

    pub fn allows_empty_sequence(&self) -> bool {
        match &self.kind {
            SegmentRuleKind::Tag { .. } => false,
            SegmentRuleKind::Concat(children) => children.iter().all(Self::allows_empty_sequence),
            SegmentRuleKind::Or(children) => children.iter().any(Self::allows_empty_sequence),
            SegmentRuleKind::ZeroOrMore(_) | SegmentRuleKind::Optional(_) => true,
            SegmentRuleKind::Sink => false,
        }
    }

    pub fn is_shift_orth_rule(&self) -> bool {
        match &self.kind {
            SegmentRuleKind::Tag { shift_orth, .. } => *shift_orth,
            SegmentRuleKind::Concat(children) | SegmentRuleKind::Or(children) => {
                children.iter().all(Self::is_shift_orth_rule)
            }
            SegmentRuleKind::ZeroOrMore(child) | SegmentRuleKind::Optional(child) => {
                child.is_shift_orth_rule()
            }
            SegmentRuleKind::Sink => false,
        }
    }

    pub fn make_shift_orth_rule(&mut self) {
        match &mut self.kind {
            SegmentRuleKind::Tag { shift_orth, .. } => *shift_orth = true,
            SegmentRuleKind::Concat(children) | SegmentRuleKind::Or(children) => {
                for child in children {
                    child.make_shift_orth_rule();
                }
            }
            SegmentRuleKind::ZeroOrMore(child) | SegmentRuleKind::Optional(child) => {
                child.make_shift_orth_rule();
            }
            SegmentRuleKind::Sink => {}
        }
    }

    pub fn atomic_rules(&self) -> Vec<&SegmentRule> {
        let mut result = Vec::new();
        self.push_atomic_rules(&mut result);
        result
    }

    fn push_atomic_rules<'a>(&'a self, result: &mut Vec<&'a SegmentRule>) {
        match &self.kind {
            SegmentRuleKind::Tag { .. } => result.push(self),
            SegmentRuleKind::Concat(children) | SegmentRuleKind::Or(children) => {
                for child in children {
                    child.push_atomic_rules(result);
                }
            }
            SegmentRuleKind::ZeroOrMore(child) | SegmentRuleKind::Optional(child) => {
                child.push_atomic_rules(result);
            }
            SegmentRuleKind::Sink => {}
        }
    }

    pub fn transform_to_generator_version(&self) -> Self {
        match &self.kind {
            SegmentRuleKind::Tag { .. } => self.clone(),
            SegmentRuleKind::ZeroOrMore(_) => {
                if self.is_shift_orth_rule() {
                    self.clone()
                } else {
                    Self::sink()
                }
            }
            SegmentRuleKind::Optional(child) => {
                if self.is_shift_orth_rule() {
                    self.clone()
                } else {
                    child.transform_to_generator_version()
                }
            }
            SegmentRuleKind::Or(children) => {
                let new_children: Vec<Self> = children
                    .iter()
                    .filter(|child| !child.allows_empty_sequence() || child.is_shift_orth_rule())
                    .map(Self::transform_to_generator_version)
                    .filter(|child| !child.is_sink_rule())
                    .collect();
                if new_children.is_empty() {
                    Self::sink()
                } else {
                    Self::or(new_children, self.line_number).set_weak(self.weak)
                }
            }
            SegmentRuleKind::Concat(children) => {
                let new_children: Vec<Self> = children
                    .iter()
                    .filter(|child| !child.allows_empty_sequence() || child.is_shift_orth_rule())
                    .map(Self::transform_to_generator_version)
                    .collect();
                if new_children.is_empty() {
                    return Self::sink();
                }
                let mut has_non_optional_non_shifting_rule = false;
                for child in &new_children {
                    if child.is_sink_rule() || has_non_optional_non_shifting_rule {
                        return Self::sink();
                    } else if !child.is_shift_orth_rule() {
                        has_non_optional_non_shifting_rule = true;
                    }
                }
                Self::concat(new_children, self.line_number).set_weak(self.weak)
            }
            SegmentRuleKind::Sink => Self::sink(),
        }
    }

    pub fn additional_atomic_rules_for_generator(&self) -> Vec<Self> {
        match &self.kind {
            SegmentRuleKind::Tag { .. } => {
                let mut rule = self.clone();
                rule.autogenerated = true;
                vec![rule]
            }
            SegmentRuleKind::ZeroOrMore(child) | SegmentRuleKind::Optional(child) => {
                child.additional_atomic_rules_for_generator()
            }
            SegmentRuleKind::Or(children) => children
                .iter()
                .flat_map(Self::additional_atomic_rules_for_generator)
                .collect(),
            SegmentRuleKind::Concat(children) => {
                let mut result = Vec::new();
                let mut current_shift_orth_rule: Option<Self> = None;
                for child in children {
                    if child.is_shift_orth_rule() {
                        current_shift_orth_rule =
                            Some(if let Some(current) = current_shift_orth_rule {
                                Self::concat(vec![current, child.clone()], child.line_number)
                            } else {
                                child.clone()
                            });
                    } else {
                        for atomic_rule in child.additional_atomic_rules_for_generator() {
                            if let Some(current) = &current_shift_orth_rule {
                                result.push(Self::concat(
                                    vec![current.clone(), atomic_rule],
                                    child.line_number,
                                ));
                            } else {
                                result.push(atomic_rule);
                            }
                        }
                        current_shift_orth_rule = None;
                    }
                }
                for rule in &mut result {
                    rule.autogenerated = true;
                }
                result
            }
            SegmentRuleKind::Sink => Vec::new(),
        }
    }

    pub fn validate_segment_rule(&self, input_name: &str) -> Result<()> {
        match &self.kind {
            SegmentRuleKind::Concat(children) => {
                for child in children {
                    child.validate_segment_rule(input_name)?;
                }
                if children.last().is_some_and(Self::is_shift_orth_rule)
                    && !children.iter().all(Self::is_shift_orth_rule)
                {
                    return Err(BuilderError::new(format!(
                        "{input_name}:{} - If the rightmost subrule of concatenation \"{}\" is with \">\", than all subrules must be with \">\"",
                        self.line_number, self
                    )));
                }
                Ok(())
            }
            SegmentRuleKind::Or(children) => {
                for child in children {
                    child.validate_segment_rule(input_name)?;
                }
                let all_shift = children.iter().all(Self::is_shift_orth_rule);
                let any_shift = children.iter().any(Self::is_shift_orth_rule);
                if !all_shift && any_shift {
                    return Err(BuilderError::new(format!(
                        "{input_name}:{} - All subrules of alternative \"{}\" must be either with or without \">\"",
                        self.line_number, self
                    )));
                }
                Ok(())
            }
            SegmentRuleKind::ZeroOrMore(child) | SegmentRuleKind::Optional(child) => {
                child.validate_segment_rule(input_name)
            }
            SegmentRuleKind::Tag { .. } | SegmentRuleKind::Sink => Ok(()),
        }
    }

    pub(super) fn add_to_segment_rules_nfa(&self, nfa: &mut SegmentRulesNfa) -> Result<()> {
        if self.is_sink_rule() {
            return Ok(());
        }
        let end_state = nfa.add_state(SegmentRulesNfaState::final_for_rule(self));
        self.add_between_segment_rules_nfa_states(nfa, nfa.initial_state, end_state)
    }

    fn add_between_segment_rules_nfa_states(
        &self,
        nfa: &mut SegmentRulesNfa,
        start_state: usize,
        end_state: usize,
    ) -> Result<()> {
        match &self.kind {
            SegmentRuleKind::Tag {
                segment_type_num,
                shift_orth,
                ..
            } => {
                let segment_type_num = u8::try_from(*segment_type_num).map_err(|_| {
                    BuilderError::new(format!(
                        "segment type number {segment_type_num} does not fit into uint8"
                    ))
                })?;
                nfa.add_transition(
                    start_state,
                    Some(SegmentRulesTransitionLabel {
                        segment_type_num,
                        shift_orth: *shift_orth,
                    }),
                    end_state,
                );
                Ok(())
            }
            SegmentRuleKind::Concat(children) => {
                let mut current_start = start_state;
                for child in &children[..children.len() - 1] {
                    let current_end = nfa.add_state(SegmentRulesNfaState::for_rule(self));
                    child.add_between_segment_rules_nfa_states(nfa, current_start, current_end)?;
                    let next_start = nfa.add_state(SegmentRulesNfaState::for_rule(self));
                    nfa.add_transition(current_end, None, next_start);
                    current_start = next_start;
                }
                children
                    .last()
                    .expect("concat is never empty")
                    .add_between_segment_rules_nfa_states(nfa, current_start, end_state)
            }
            SegmentRuleKind::Or(children) => {
                for child in children {
                    let intermediate_start = nfa.add_state(SegmentRulesNfaState::for_rule(self));
                    let intermediate_end = nfa.add_state(SegmentRulesNfaState::for_rule(self));
                    nfa.add_transition(start_state, None, intermediate_start);
                    child.add_between_segment_rules_nfa_states(
                        nfa,
                        intermediate_start,
                        intermediate_end,
                    )?;
                    nfa.add_transition(intermediate_end, None, end_state);
                }
                Ok(())
            }
            SegmentRuleKind::ZeroOrMore(child) => {
                let intermediate_start = nfa.add_state(SegmentRulesNfaState::for_rule(self));
                let intermediate_end = nfa.add_state(SegmentRulesNfaState::for_rule(self));
                nfa.add_transition(start_state, None, intermediate_start);
                nfa.add_transition(start_state, None, end_state);
                child.add_between_segment_rules_nfa_states(
                    nfa,
                    intermediate_start,
                    intermediate_end,
                )?;
                nfa.add_transition(intermediate_end, None, end_state);
                nfa.add_transition(intermediate_end, None, intermediate_start);
                Ok(())
            }
            SegmentRuleKind::Optional(child) => {
                let intermediate_start = nfa.add_state(SegmentRulesNfaState::for_rule(self));
                let intermediate_end = nfa.add_state(SegmentRulesNfaState::for_rule(self));
                nfa.add_transition(start_state, None, intermediate_start);
                nfa.add_transition(start_state, None, end_state);
                child.add_between_segment_rules_nfa_states(
                    nfa,
                    intermediate_start,
                    intermediate_end,
                )?;
                nfa.add_transition(intermediate_end, None, end_state);
                Ok(())
            }
            SegmentRuleKind::Sink => Ok(()),
        }
    }

    pub(super) fn collect_atomic_rule_info(&self, atoms: &mut Vec<SegmentRuleAtom>) {
        match &self.kind {
            SegmentRuleKind::Tag {
                segment_type_num,
                shift_orth,
                segment_type,
            } => atoms.push(SegmentRuleAtom {
                segment_type_num: *segment_type_num,
                shift_orth: *shift_orth,
                segment_type: segment_type.clone(),
            }),
            SegmentRuleKind::Concat(children) | SegmentRuleKind::Or(children) => {
                for child in children {
                    child.collect_atomic_rule_info(atoms);
                }
            }
            SegmentRuleKind::ZeroOrMore(child) | SegmentRuleKind::Optional(child) => {
                child.collect_atomic_rule_info(atoms);
            }
            SegmentRuleKind::Sink => {}
        }
    }

    pub(super) fn remap_shift_orth_segment_types(
        &mut self,
        shift_orth_map: &BTreeMap<usize, usize>,
    ) {
        match &mut self.kind {
            SegmentRuleKind::Tag {
                segment_type_num,
                shift_orth,
                ..
            } => {
                if *shift_orth {
                    if let Some(new_segment_type_num) = shift_orth_map.get(segment_type_num) {
                        *segment_type_num = *new_segment_type_num;
                    }
                }
            }
            SegmentRuleKind::Concat(children) | SegmentRuleKind::Or(children) => {
                for child in children {
                    child.remap_shift_orth_segment_types(shift_orth_map);
                }
            }
            SegmentRuleKind::ZeroOrMore(child) | SegmentRuleKind::Optional(child) => {
                child.remap_shift_orth_segment_types(shift_orth_map);
            }
            SegmentRuleKind::Sink => {}
        }
    }
}

impl fmt::Display for SegmentRule {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match &self.kind {
            SegmentRuleKind::Tag {
                segment_type,
                shift_orth,
                ..
            } => {
                f.write_str(segment_type)?;
                if *shift_orth {
                    f.write_str(">")?;
                }
                Ok(())
            }
            SegmentRuleKind::Concat(children) => {
                for (index, child) in children.iter().enumerate() {
                    if index > 0 {
                        f.write_str(" ")?;
                    }
                    write!(f, "{child}")?;
                }
                Ok(())
            }
            SegmentRuleKind::Or(children) => {
                for (index, child) in children.iter().enumerate() {
                    if index > 0 {
                        f.write_str(" | ")?;
                    }
                    write!(f, "{child}")?;
                }
                Ok(())
            }
            SegmentRuleKind::ZeroOrMore(child) => write!(f, "({child})*"),
            SegmentRuleKind::Optional(child) => write!(f, "({child})?"),
            SegmentRuleKind::Sink => f.write_str("<<REMOVED>>"),
        }
    }
}
